import sublime, sublime_plugin
import re

def match(rex, str):
    m = rex.match(str)
    if m:
        return m.group(0)
    else:
        return None

class PowerModifierCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        # if not view.match_selector(locations[0],
        #         "text.html - source"):
        #     return []

        pt = locations[0] - len(prefix) - 1
        ch = view.substr(sublime.Region(pt, pt + 1))
        if ch != ' ':
            return []

        return ([

            ("absolute=\"\"\tPowerCMS[M]", "absolute=\"${1}\""),
            ("abs_addslash=\"\"\tPowerCMS[M]", "abs_addslash=\"${1}\""),
            ("accessibility=\"\"\tPowerCMS[M]", "accessibility=\"${1}\""),
            ("add_session_for_mobile=\"\"\tPowerCMS[M]", "add_session_for_mobile=\"${1}\""),
            ("asset2url=\"\"\tPowerCMS[M]", "asset2url=\"${1}\""),
            ("asset_id=\"\"\tPowerCMS[M]", "asset_id=\"${1}\""),
            ("build_mtml=\"\"\tPowerCMS[M]", "build_mtml=\"${1}\""),
            ("convert2thumbnail=\"\"\tPowerCMS[M]", "convert2thumbnail=\"${1}\""),
            ("convertthumbnail=\"\"\tPowerCMS[M]", "convertthumbnail=\"${1}\""),
            ("cut_firstslash=\"\"\tPowerCMS[M]", "cut_firstslash=\"${1}\""),
            ("emoticon2mtml=\"\"\tPowerCMS[M]", "emoticon2mtml=\"${1}\""),
            ("exportformat=\"\"\tPowerCMS[M]", "exportformat=\"${1}\""),
            ("external_link_for_mobile=\"\"\tPowerCMS[M]", "external_link_for_mobile=\"${1}\""),
            ("format_ts=\"\"\tPowerCMS[M]", "format_ts=\"${1}\""),
            ("get_basename=\"\"\tPowerCMS[M]", "get_basename=\"${1}\""),
            ("highlight=\"\"\tPowerCMS[M]", "highlight=\"${1}\""),
            ("hilight=\"\"\tPowerCMS[M]", "hilight=\"${1}\""),
            ("HTMLImageElement=\"\"\tPowerCMS[M]", "HTMLImageElement=\"${1}\""),
            ("is_draft=\"\"\tPowerCMS[M]", "is_draft=\"${1}\""),
            ("path2url=\"\"\tPowerCMS[M]", "path2url=\"${1}\""),
            ("pickup_extension=\"\"\tPowerCMS[M]", "pickup_extension=\"${1}\""),
            ("set_loop=\"\"\tPowerCMS[M]", "set_loop=\"${1}\""),
            ("str2keitai=\"\"\tPowerCMS[M]", "str2keitai=\"${1}\""),
            ("strip_emptylines=\"\"\tPowerCMS[M]", "strip_emptylines=\"${1}\""),
            ("tab2table=\"\"\tPowerCMS[M]", "tab2table=\"${1}\""),
            ("table2tag=\"\"\tPowerCMS[M]", "table2tag=\"${1}\""),
            ("tel2link=\"\"\tPowerCMS[M]", "tel2link=\"${1}\""),
            ("translate_templatized=\"\"\tPowerCMS[M]", "translate_templatized=\"${1}\""),
            ("trimj_to=\"\"\tPowerCMS[M]", "trimj_to=\"${1}\""),
            ("url2download=\"\"\tPowerCMS[M]", "url2download=\"${1}\""),
            ("z2h=\"\"\tPowerCMS[M]", "z2h=\"${1}\"")


        ], sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS)

class PowerMTTagCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        # if not view.match_selector(locations[0],
        #         "text.html - source"):
        #     return []

        pt = locations[0] - len(prefix) - 1
        ch = view.substr(sublime.Region(pt, pt + 1))
        if ch != '<':
            return []

        return ([
            # Block Tag

            ("mt:AccessibleBlock\tPowerCMS[B]", "mt:AccessibleBlock${1}>${2}</mt:AccessibleBlock>"),
            ("mt:AccessibleBlock\tPowerCMS[B]", "mt:AccessibleBlock${1}>${2}</mt:AccessibleBlock>"),
            ("mt:AltSearchMetadata\tPowerCMS[B]", "mt:AltSearchMetadata${1}>${2}</mt:AltSearchMetadata>"),
            ("mt:AltSearchMetadatas\tPowerCMS[B]", "mt:AltSearchMetadatas${1}>${2}</mt:AltSearchMetadatas>"),
            ("mt:AltSearchResults\tPowerCMS[B]", "mt:AltSearchResults${1}>${2}</mt:AltSearchResults>"),
            ("mt:Banner\tPowerCMS[B]", "mt:Banner${1}>${2}</mt:Banner>"),
            ("mt:BannerAsset\tPowerCMS[B]", "mt:BannerAsset${1}>${2}</mt:BannerAsset>"),
            ("mt:BannerAuthor\tPowerCMS[B]", "mt:BannerAuthor${1}>${2}</mt:BannerAuthor>"),
            ("mt:BannerRandom\tPowerCMS[B]", "mt:BannerRandom${1}>${2}</mt:BannerRandom>"),
            ("mt:Banners\tPowerCMS[B]", "mt:Banners${1}>${2}</mt:Banners>"),
            ("mt:BannersFooter\tPowerCMS[B]", "mt:BannersFooter>${1}</mt:BannersFooter>"),
            ("mt:BannersHeader\tPowerCMS[B]", "mt:BannersHeader>${1}</mt:BannersHeader>"),
            ("mt:BannerTags\tPowerCMS[B]", "mt:BannerTags${1}>${2}</mt:BannerTags>"),
            ("mt:BlogAttachFiles\tPowerCMS[B]", "mt:BlogAttachFiles${1}>${2}</mt:BlogAttachFiles>"),
            ("mt:BlogTreeAssets\tPowerCMS[B]", "mt:BlogTreeAssets${1}>${2}</mt:BlogTreeAssets>"),
            ("mt:BlogTreeAssetsFooter\tPowerCMS[B]", "mt:BlogTreeAssetsFooter>${1}</mt:BlogTreeAssetsFooter>"),
            ("mt:BlogTreeAssetsHeader\tPowerCMS[B]", "mt:BlogTreeAssetsHeader>${1}</mt:BlogTreeAssetsHeader>"),
            ("mt:BlogTreeEntries\tPowerCMS[B]", "mt:BlogTreeEntries${1}>${2}</mt:BlogTreeEntries>"),
            ("mt:BlogTreeEntriesFooter\tPowerCMS[B]", "mt:BlogTreeEntriesFooter>${1}</mt:BlogTreeEntriesFooter>"),
            ("mt:BlogTreeEntriesHeader\tPowerCMS[B]", "mt:BlogTreeEntriesHeader>${1}</mt:BlogTreeEntriesHeader>"),
            ("mt:Breadcrumbs\tPowerCMS[B]", "mt:Breadcrumbs${1}>${2}</mt:Breadcrumbs>"),
            ("mt:Campaign\tPowerCMS[B]", "mt:Campaign${1}>${2}</mt:Campaign>"),
            ("mt:CampaignAsset\tPowerCMS[B]", "mt:CampaignAsset${1}>${2}</mt:CampaignAsset>"),
            ("mt:CampaignAuthor\tPowerCMS[B]", "mt:CampaignAuthor${1}>${2}</mt:CampaignAuthor>"),
            ("mt:CampaignRandom\tPowerCMS[B]", "mt:CampaignRandom${1}>${2}</mt:CampaignRandom>"),
            ("mt:Campaigns\tPowerCMS[B]", "mt:Campaigns${1}>${2}</mt:Campaigns>"),
            ("mt:CampaignsFooter\tPowerCMS[B]", "mt:CampaignsFooter>${1}</mt:CampaignsFooter>"),
            ("mt:CampaignsHeader\tPowerCMS[B]", "mt:CampaignsHeader>${1}</mt:CampaignsHeader>"),
            ("mt:CampaignTags\tPowerCMS[B]", "mt:CampaignTags${1}>${2}</mt:CampaignTags>"),
            ("mt:CategoryAttachFiles\tPowerCMS[B]", "mt:CategoryAttachFiles${1}>${2}</mt:CategoryAttachFiles>"),
            ("mt:CfEntrySetContext\tPowerCMS[B]", "mt:CfEntrySetContext${1}>${2}</mt:CfEntrySetContext>"),
            ("mt:CMSBlogContext\tPowerCMS[B]", "mt:CMSBlogContext${1}>${2}</mt:CMSBlogContext>"),
            ("mt:CMSCacheBlock\tPowerCMS[B]", "mt:CMSCacheBlock${1}>${2}</mt:CMSCacheBlock>"),
            ("mt:CMSContext\tPowerCMS[B]", "mt:CMSContext${1}>${2}</mt:CMSContext>"),
            ("mt:ContactFormFileAsset\tPowerCMS[B]", "mt:ContactFormFileAsset${1}>${2}</mt:ContactFormFileAsset>"),
            ("mt:ContactForms\tPowerCMS[B]", "mt:ContactForms${1}>${2}</mt:ContactForms>"),
            ("mt:ConvertSJIS\tPowerCMS[B]", "mt:ConvertSJIS${1}>${2}</mt:ConvertSJIS>"),
            ("mt:CountGroupBy\tPowerCMS[B]", "mt:CountGroupBy${1}>${2}</mt:CountGroupBy>"),
            ("mt:CSSCompressor\tPowerCMS[B]", "mt:CSSCompressor${1}>${2}</mt:CSSCompressor>"),
            ("mt:CustomConfig\tPowerCMS[B]", "mt:CustomConfig${1}>${2}</mt:CustomConfig>"),
            ("mt:CustomConfigLoop\tPowerCMS[B]", "mt:CustomConfigLoop${1}>${2}</mt:CustomConfigLoop>"),
            ("mt:CustomGroups\tPowerCMS[B]", "mt:CustomGroups${1}>${2}</mt:CustomGroups>"),
            ("mt:CustomGroupsFooter\tPowerCMS[B]", "mt:CustomGroupsFooter>${1}</mt:CustomGroupsFooter>"),
            ("mt:CustomGroupsHeader\tPowerCMS[B]", "mt:CustomGroupsHeader>${1}</mt:CustomGroupsHeader>"),
            ("mt:CustomObject\tPowerCMS[B]", "mt:CustomObject${1}>${2}</mt:CustomObject>"),
            ("mt:CustomObjectAuthor\tPowerCMS[B]", "mt:CustomObjectAuthor${1}>${2}</mt:CustomObjectAuthor>"),
            ("mt:CustomObjectColumns\tPowerCMS[B]", "mt:CustomObjectColumns${1}>${2}</mt:CustomObjectColumns>"),
            ("mt:CustomObjectColumnsFooter\tPowerCMS[B]", "mt:CustomObjectColumnsFooter>${1}</mt:CustomObjectColumnsFooter>"),
            ("mt:CustomObjectColumnsHeader\tPowerCMS[B]", "mt:CustomObjectColumnsHeader>${1}</mt:CustomObjectColumnsHeader>"),
            ("mt:CustomObjectFolder\tPowerCMS[B]", "mt:CustomObjectFolder${1}>${2}</mt:CustomObjectFolder>"),
            ("mt:CustomObjects\tPowerCMS[B]", "mt:CustomObjects${1}>${2}</mt:CustomObjects>"),
            ("mt:CustomObjectsFooter\tPowerCMS[B]", "mt:CustomObjectsFooter>${1}</mt:CustomObjectsFooter>"),
            ("mt:CustomObjectsHeader\tPowerCMS[B]", "mt:CustomObjectsHeader>${1}</mt:CustomObjectsHeader>"),
            ("mt:CustomObjectTags\tPowerCMS[B]", "mt:CustomObjectTags${1}>${2}</mt:CustomObjectTags>"),
            ("mt:Emoticon2emoji\tPowerCMS[B]", "mt:Emoticon2emoji${1}>${2}</mt:Emoticon2emoji>"),
            ("mt:EntryAttachFiles\tPowerCMS[B]", "mt:EntryAttachFiles${1}>${2}</mt:EntryAttachFiles>"),
            ("mt:EntryChildrenNext\tPowerCMS[B]", "mt:EntryChildrenNext${1}>${2}</mt:EntryChildrenNext>"),
            ("mt:EntryChildrenPages\tPowerCMS[B]", "mt:EntryChildrenPages${1}>${2}</mt:EntryChildrenPages>"),
            ("mt:EntryChildrenPagesFooter\tPowerCMS[B]", "mt:EntryChildrenPagesFooter>${1}</mt:EntryChildrenPagesFooter>"),
            ("mt:EntryChildrenPagesHeader\tPowerCMS[B]", "mt:EntryChildrenPagesHeader>${1}</mt:EntryChildrenPagesHeader>"),
            ("mt:EntryChildrenPrev\tPowerCMS[B]", "mt:EntryChildrenPrev${1}>${2}</mt:EntryChildrenPrev>"),
            ("mt:EntryCreatorContext\tPowerCMS[B]", "mt:EntryCreatorContext${1}>${2}</mt:EntryCreatorContext>"),
            ("mt:EntryPosts\tPowerCMS[B]", "mt:EntryPosts${1}>${2}</mt:EntryPosts>"),
            ("mt:EstraierBlock\tPowerCMS[B]", "mt:EstraierBlock${1}>${2}</mt:EstraierBlock>"),
            ("mt:EstraierMeta\tPowerCMS[B]", "mt:EstraierMeta${1}>${2}</mt:EstraierMeta>"),
            ("mt:EstraierResults\tPowerCMS[B]", "mt:EstraierResults${1}>${2}</mt:EstraierResults>"),
            ("mt:EstraierSuffix\tPowerCMS[B]", "mt:EstraierSuffix${1}>${2}</mt:EstraierSuffix>"),
            ("mt:EstraierTarget\tPowerCMS[B]", "mt:EstraierTarget${1}>${2}</mt:EstraierTarget>"),
            ("mt:EstResultBlogCtx\tPowerCMS[B]", "mt:EstResultBlogCtx${1}>${2}</mt:EstResultBlogCtx>"),
            ("mt:EstResultEntryCtx\tPowerCMS[B]", "mt:EstResultEntryCtx${1}>${2}</mt:EstResultEntryCtx>"),
            ("mt:EstResultFooter\tPowerCMS[B]", "mt:EstResultFooter>${1}</mt:EstResultFooter>"),
            ("mt:EstResultHeader\tPowerCMS[B]", "mt:EstResultHeader>${1}</mt:EstResultHeader>"),
            ("mt:EstResultPager\tPowerCMS[B]", "mt:EstResultPager${1}>${2}</mt:EstResultPager>"),
            ("mt:EstResultPagerFooter\tPowerCMS[B]", "mt:EstResultPagerFooter>${1}</mt:EstResultPagerFooter>"),
            ("mt:EstResultPagerHeader\tPowerCMS[B]", "mt:EstResultPagerHeader>${1}</mt:EstResultPagerHeader>"),
            ("mt:ExportEntries\tPowerCMS[B]", "mt:ExportEntries${1}>${2}</mt:ExportEntries>"),
            ("mt:ExtFieldAsset\tPowerCMS[B]", "mt:ExtFieldAsset${1}>${2}</mt:ExtFieldAsset>"),
            ("mt:ExtFields\tPowerCMS[B]", "mt:ExtFields${1}>${2}</mt:ExtFields>"),
            ("mt:ExtFieldsMultiValues\tPowerCMS[B]", "mt:ExtFieldsMultiValues${1}>${2}</mt:ExtFieldsMultiValues>"),
            ("mt:FormElementOptions\tPowerCMS[B]", "mt:FormElementOptions${1}>${2}</mt:FormElementOptions>"),
            ("mt:GAHotEntries\tPowerCMS[B]", "mt:GAHotEntries${1}>${2}</mt:GAHotEntries>"),
            ("mt:GroupAssets\tPowerCMS[B]", "mt:GroupAssets${1}>${2}</mt:GroupAssets>"),
            ("mt:GroupAssetsFooter\tPowerCMS[B]", "mt:GroupAssetsFooter>${1}</mt:GroupAssetsFooter>"),
            ("mt:GroupAssetsHeader\tPowerCMS[B]", "mt:GroupAssetsHeader>${1}</mt:GroupAssetsHeader>"),
            ("mt:GroupBlogs\tPowerCMS[B]", "mt:GroupBlogs${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</mt:GroupBlogs>"),
            ("mt:GroupBlogsFooter\tPowerCMS[B]", "mt:GroupBlogsFooter>${1}</mt:GroupBlogsFooter>"),
            ("mt:GroupBlogsHeader\tPowerCMS[B]", "mt:GroupBlogsHeader>${1}</mt:GroupBlogsHeader>"),
            ("mt:GroupBlogsWebsites\tPowerCMS[B]", "mt:GroupBlogsWebsites${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</mt:GroupBlogsWebsites>"),
            ("mt:GroupBlogsWebsitesFooter\tPowerCMS[B]", "mt:GroupBlogsWebsitesFooter>${1}</mt:GroupBlogsWebsitesFooter>"),
            ("mt:GroupBlogsWebsitesHeader\tPowerCMS[B]", "mt:GroupBlogsWebsitesHeader>${1}</mt:GroupBlogsWebsitesHeader>"),
            ("mt:GroupCategories\tPowerCMS[B]", "mt:GroupCategories${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</mt:GroupCategories>"),
            ("mt:GroupCategoriesFolders\tPowerCMS[B]", "mt:GroupCategoriesFolders${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</mt:GroupCategoriesFolders>"),
            ("mt:GroupCategoriesFoldersFooter\tPowerCMS[B]", "mt:GroupCategoriesFoldersFooter>${1}</mt:GroupCategoriesFoldersFooter>"),
            ("mt:GroupCategoriesFoldersHeader\tPowerCMS[B]", "mt:GroupCategoriesFoldersHeader>${1}</mt:GroupCategoriesFoldersHeader>"),
            ("mt:GroupCategoriesFooter\tPowerCMS[B]", "mt:GroupCategoriesFooter>${1}</mt:GroupCategoriesFooter>"),
            ("mt:GroupCategoriesHeader\tPowerCMS[B]", "mt:GroupCategoriesHeader>${1}</mt:GroupCategoriesHeader>"),
            ("mt:GroupEntries\tPowerCMS[B]", "mt:GroupEntries${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</mt:GroupEntries>"),
            ("mt:GroupEntriesFooter\tPowerCMS[B]", "mt:GroupEntriesFooter>${1}</mt:GroupEntriesFooter>"),
            ("mt:GroupEntriesHeader\tPowerCMS[B]", "mt:GroupEntriesHeader>${1}</mt:GroupEntriesHeader>"),
            ("mt:GroupEntriesPages\tPowerCMS[B]", "mt:GroupEntriesPages${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</mt:GroupEntriesPages>"),
            ("mt:GroupEntriesPagesFooter\tPowerCMS[B]", "mt:GroupEntriesPagesFooter>${1}</mt:GroupEntriesPagesFooter>"),
            ("mt:GroupEntriesPagesHeader\tPowerCMS[B]", "mt:GroupEntriesPagesHeader>${1}</mt:GroupEntriesPagesHeader>"),
            ("mt:GroupFolders\tPowerCMS[B]", "mt:GroupFolders${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</mt:GroupFolders>"),
            ("mt:GroupFoldersFooter\tPowerCMS[B]", "mt:GroupFoldersFooter>${1}</mt:GroupFoldersFooter>"),
            ("mt:GroupFoldersHeader\tPowerCMS[B]", "mt:GroupFoldersHeader>${1}</mt:GroupFoldersHeader>"),
            ("mt:GroupPages\tPowerCMS[B]", "mt:GroupPages${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</mt:GroupPages>"),
            ("mt:GroupPagesFooter\tPowerCMS[B]", "mt:GroupPagesFooter>${1}</mt:GroupPagesFooter>"),
            ("mt:GroupPagesHeader\tPowerCMS[B]", "mt:GroupPagesHeader>${1}</mt:GroupPagesHeader>"),
            ("mt:GroupWebsites\tPowerCMS[B]", "mt:GroupWebsites${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</mt:GroupWebsites>"),
            ("mt:GroupWebsitesFooter\tPowerCMS[B]", "mt:GroupWebsitesFooter>${1}</mt:GroupWebsitesFooter>"),
            ("mt:GroupWebsitesHeader\tPowerCMS[B]", "mt:GroupWebsitesHeader>${1}</mt:GroupWebsitesHeader>"),
            ("mt:IfEntryChildrenFooter\tPowerCMS[B]", "mt:IfEntryChildrenFooter>${1}</mt:IfEntryChildrenFooter>"),
            ("mt:IfEntryChildrenHeader\tPowerCMS[B]", "mt:IfEntryChildrenHeader>${1}</mt:IfEntryChildrenHeader>"),
            ("mt:ImgAltCheck\tPowerCMS[B]", "mt:ImgAltCheck${1}>${2}</mt:ImgAltCheck>"),
            ("mt:ImgAltCheckFooter\tPowerCMS[B]", "mt:ImgAltCheckFooter>${1}</mt:ImgAltCheckFooter>"),
            ("mt:ImgAltCheckHeader\tPowerCMS[B]", "mt:ImgAltCheckHeader>${1}</mt:ImgAltCheckHeader>"),
            ("mt:ItemGroupAssets\tPowerCMS[B]", "mt:ItemGroupAssets${1}>${2}</mt:ItemGroupAssets>"),
            ("mt:ItemGroupAssetsFooter\tPowerCMS[B]", "mt:ItemGroupAssetsFooter>${1}</mt:ItemGroupAssetsFooter>"),
            ("mt:ItemGroupAssetsHeader\tPowerCMS[B]", "mt:ItemGroupAssetsHeader>${1}</mt:ItemGroupAssetsHeader>"),
            ("mt:ItemGroupBlogNext\tPowerCMS[B]", "mt:ItemGroupBlogNext${1}>${2}</mt:ItemGroupBlogNext>"),
            ("mt:ItemGroupBlogPrevious\tPowerCMS[B]", "mt:ItemGroupBlogPrevious${1}>${2}</mt:ItemGroupBlogPrevious>"),
            ("mt:ItemGroupBlogs\tPowerCMS[B]", "mt:ItemGroupBlogs${1}>${2}</mt:ItemGroupBlogs>"),
            ("mt:ItemGroupBlogsFooter\tPowerCMS[B]", "mt:ItemGroupBlogsFooter>${1}</mt:ItemGroupBlogsFooter>"),
            ("mt:ItemGroupBlogsHeader\tPowerCMS[B]", "mt:ItemGroupBlogsHeader>${1}</mt:ItemGroupBlogsHeader>"),
            ("mt:ItemGroupCategories\tPowerCMS[B]", "mt:ItemGroupCategories${1}>${2}</mt:ItemGroupCategories>"),
            ("mt:ItemGroupCategoriesFooter\tPowerCMS[B]", "mt:ItemGroupCategoriesFooter>${1}</mt:ItemGroupCategoriesFooter>"),
            ("mt:ItemGroupCategoriesHeader\tPowerCMS[B]", "mt:ItemGroupCategoriesHeader>${1}</mt:ItemGroupCategoriesHeader>"),
            ("mt:ItemGroupCategoryNext\tPowerCMS[B]", "mt:ItemGroupCategoryNext${1}>${2}</mt:ItemGroupCategoryNext>"),
            ("mt:ItemGroupCategoryPrevious\tPowerCMS[B]", "mt:ItemGroupCategoryPrevious${1}>${2}</mt:ItemGroupCategoryPrevious>"),
            ("mt:ItemGroupEntries\tPowerCMS[B]", "mt:ItemGroupEntries${1}>${2}</mt:ItemGroupEntries>"),
            ("mt:ItemGroupEntriesFooter\tPowerCMS[B]", "mt:ItemGroupEntriesFooter>${1}</mt:ItemGroupEntriesFooter>"),
            ("mt:ItemGroupEntriesHeader\tPowerCMS[B]", "mt:ItemGroupEntriesHeader>${1}</mt:ItemGroupEntriesHeader>"),
            ("mt:ItemGroupEntryNext\tPowerCMS[B]", "mt:ItemGroupEntryNext${1}>${2}</mt:ItemGroupEntryNext>"),
            ("mt:ItemGroupEntryPrevious\tPowerCMS[B]", "mt:ItemGroupEntryPrevious${1}>${2}</mt:ItemGroupEntryPrevious>"),
            ("mt:JSCompressor\tPowerCMS[B]", "mt:JSCompressor${1}>${2}</mt:JSCompressor>"),
            ("mt:KeitaiContent\tPowerCMS[B]", "mt:KeitaiContent${1}>${2}</mt:KeitaiContent>"),
            ("mt:KeitaiContentBody\tPowerCMS[B]", "mt:KeitaiContentBody${1}>${2}</mt:KeitaiContentBody>"),
            ("mt:KeitaiContentPageList\tPowerCMS[B]", "mt:KeitaiContentPageList${1}>${2}</mt:KeitaiContentPageList>"),
            ("mt:KeitaiContentPageListFooter\tPowerCMS[B]", "mt:KeitaiContentPageListFooter>${1}</mt:KeitaiContentPageListFooter>"),
            ("mt:KeitaiContentPageListHeader\tPowerCMS[B]", "mt:KeitaiContentPageListHeader>${1}</mt:KeitaiContentPageListHeader>"),
            ("mt:LinkAuthor\tPowerCMS[B]", "mt:LinkAuthor${1}>${2}</mt:LinkAuthor>"),
            ("mt:LinkBlock\tPowerCMS[B]", "mt:LinkBlock${1}>${2}</mt:LinkBlock>"),
            ("mt:Links\tPowerCMS[B]", "mt:Links${1}>${2}</mt:Links>"),
            ("mt:LinksFooter\tPowerCMS[B]", "mt:LinksFooter>${1}</mt:LinksFooter>"),
            ("mt:LinksHeader\tPowerCMS[B]", "mt:LinksHeader>${1}</mt:LinksHeader>"),
            ("mt:LinkTags\tPowerCMS[B]", "mt:LinkTags${1}>${2}</mt:LinkTags>"),
            ("mt:ObjectGroupItems\tPowerCMS[B]", "mt:ObjectGroupItems${1}>${2}</mt:ObjectGroupItems>"),
            ("mt:OGBlogs\tPowerCMS[B]", "mt:OGBlogs${1}>${2}</mt:OGBlogs>"),
            ("mt:OGCategories\tPowerCMS[B]", "mt:OGCategories${1}>${2}</mt:OGCategories>"),
            ("mt:OGEntries\tPowerCMS[B]", "mt:OGEntries${1}>${2}</mt:OGEntries>"),
            ("mt:PageParentEntry\tPowerCMS[B]", "mt:PageParentEntry${1}>${2}</mt:PageParentEntry>"),
            ("mt:Pager\tPowerCMS[B]", "mt:Pager${1}>${2}</mt:Pager>"),
            ("mt:PagerBlock\tPowerCMS[B]", "mt:PagerBlock${1}>${2}</mt:PagerBlock>"),
            ("mt:RemoveReturn\tPowerCMS[B]", "mt:RemoveReturn${1}>${2}</mt:RemoveReturn>"),
            ("mt:RequestCache\tPowerCMS[B]", "mt:RequestCache${1}>${2}</mt:RequestCache>"),
            ("mt:RequestCacheBlock\tPowerCMS[B]", "mt:RequestCacheBlock${1}>${2}</mt:RequestCacheBlock>"),
            ("mt:SearchEntryField\tPowerCMS[B]", "mt:SearchEntryField${1}>${2}</mt:SearchEntryField>"),
            ("mt:SetContext\tPowerCMS[B]", "mt:SetContext${1}>${2}</mt:SetContext>"),
            ("mt:SetErrorHandler\tPowerCMS[B]", "mt:SetErrorHandler${1}>${2}</mt:SetErrorHandler>"),
            ("mt:SetFolderContext\tPowerCMS[B]", "mt:SetFolderContext${1}>${2}</mt:SetFolderContext>"),
            ("mt:SetTagContext\tPowerCMS[B]", "mt:SetTagContext${1}>${2}</mt:SetTagContext>"),
            ("mt:StripLineFeeds\tPowerCMS[B]", "mt:StripLineFeeds${1}>${2}</mt:StripLineFeeds>"),
            ("mt:StripTags\tPowerCMS[B]", "mt:StripTags${1}>${2}</mt:StripTags>"),
            ("mt:TabSplitData\tPowerCMS[B]", "mt:TabSplitData${1}>${2}</mt:TabSplitData>"),
            ("mt:TabSplitDatas\tPowerCMS[B]", "mt:TabSplitDatas${1}>${2}</mt:TabSplitDatas>"),
            ("mt:Templates\tPowerCMS[B]", "mt:Templates${1}>${2}</mt:Templates>"),
            ("mt:TemplatesFooter\tPowerCMS[B]", "mt:TemplatesFooter>${1}</mt:TemplatesFooter>"),
            ("mt:TemplatesHeader\tPowerCMS[B]", "mt:TemplatesHeader>${1}</mt:TemplatesHeader>"),
            ("mt:UserBookmarks\tPowerCMS[B]", "mt:UserBookmarks${1}>${2}</mt:UserBookmarks>"),
            ("mt:ViewerUserContext\tPowerCMS[B]", "mt:ViewerUserContext${1}>${2}</mt:ViewerUserContext>"),
            ("mt:Years\tPowerCMS[B]", "mt:Years${1}>${2}</mt:Years>"),


            # Conditional Tag

            ("mt:BannerIfTagged\tPowerCMS[C]", "mt:BannerIfTagged${1}>${2}</mt:BannerIfTagged>"),
            ("mt:CampaignIfTagged\tPowerCMS[C]", "mt:CampaignIfTagged${1}>${2}</mt:CampaignIfTagged>"),
            ("mt:CustomObjectIfTagged\tPowerCMS[C]", "mt:CustomObjectIfTagged${1}>${2}</mt:CustomObjectIfTagged>"),
            ("mt:IfActiveImage\tPowerCMS[C]", "mt:IfActiveImage${1}>${2}</mt:IfActiveImage>"),
            ("mt:IfActiveLink\tPowerCMS[C]", "mt:IfActiveLink${1}>${2}</mt:IfActiveLink>"),
            ("mt:IfActiveRSS\tPowerCMS[C]", "mt:IfActiveRSS${1}>${2}</mt:IfActiveRSS>"),
            ("mt:IfAltsearchAnd_or\tPowerCMS[C]", "mt:IfAltsearchAnd_or${1}>${2}</mt:IfAltsearchAnd_or>"),
            ("mt:IfAltsearchCategories_and_or\tPowerCMS[C]", "mt:IfAltsearchCategories_and_or${1}>${2}</mt:IfAltsearchCategories_and_or>"),
            ("mt:IfAltsearchCurrentCategories\tPowerCMS[C]", "mt:IfAltsearchCurrentCategories${1}>${2}</mt:IfAltsearchCurrentCategories>"),
            ("mt:IfAltsearchCurrentCategory\tPowerCMS[C]", "mt:IfAltsearchCurrentCategory${1}>${2}</mt:IfAltsearchCurrentCategory>"),
            ("mt:IfAltsearchDate\tPowerCMS[C]", "mt:IfAltsearchDate${1}>${2}</mt:IfAltsearchDate>"),
            ("mt:IfAltsearchFrom\tPowerCMS[C]", "mt:IfAltsearchFrom${1}>${2}</mt:IfAltsearchFrom>"),
            ("mt:IfAltsearchMatchQuery\tPowerCMS[C]", "mt:IfAltsearchMatchQuery${1}>${2}</mt:IfAltsearchMatchQuery>"),
            ("mt:IfAltsearchMetadatasFooter\tPowerCMS[C]", "mt:IfAltsearchMetadatasFooter>${1}</mt:IfAltsearchMetadatasFooter>"),
            ("mt:IfAltsearchMetadatasHeader\tPowerCMS[C]", "mt:IfAltsearchMetadatasHeader>${1}</mt:IfAltsearchMetadatasHeader>"),
            ("mt:IfAltsearchModeIsCategories\tPowerCMS[C]", "mt:IfAltsearchModeIsCategories${1}>${2}</mt:IfAltsearchModeIsCategories>"),
            ("mt:IfAltsearchModeIsCategory\tPowerCMS[C]", "mt:IfAltsearchModeIsCategory${1}>${2}</mt:IfAltsearchModeIsCategory>"),
            ("mt:IfAltsearchModeIsSubCategory\tPowerCMS[C]", "mt:IfAltsearchModeIsSubCategory${1}>${2}</mt:IfAltsearchModeIsSubCategory>"),
            ("mt:IfAltsearchModeIsTag\tPowerCMS[C]", "mt:IfAltsearchModeIsTag${1}>${2}</mt:IfAltsearchModeIsTag>"),
            ("mt:IfAltsearchNoneMatch\tPowerCMS[C]", "mt:IfAltsearchNoneMatch${1}>${2}</mt:IfAltsearchNoneMatch>"),
            ("mt:IfAltsearchParam\tPowerCMS[C]", "mt:IfAltsearchParam${1}>${2}</mt:IfAltsearchParam>"),
            ("mt:IfAltSearchParamDate\tPowerCMS[C]", "mt:IfAltSearchParamDate${1}>${2}</mt:IfAltSearchParamDate>"),
            ("mt:IfAltsearchQuery\tPowerCMS[C]", "mt:IfAltsearchQuery${1}>${2}</mt:IfAltsearchQuery>"),
            ("mt:IfAltsearchResultCurrent\tPowerCMS[C]", "mt:IfAltsearchResultCurrent${1}>${2}</mt:IfAltsearchResultCurrent>"),
            ("mt:IfAltsearchResultNext\tPowerCMS[C]", "mt:IfAltsearchResultNext${1}>${2}</mt:IfAltsearchResultNext>"),
            ("mt:IfAltsearchResultPrev\tPowerCMS[C]", "mt:IfAltsearchResultPrev${1}>${2}</mt:IfAltsearchResultPrev>"),
            ("mt:IfAltsearchSort_by\tPowerCMS[C]", "mt:IfAltsearchSort_by${1}>${2}</mt:IfAltsearchSort_by>"),
            ("mt:IfAltsearchSort_order\tPowerCMS[C]", "mt:IfAltsearchSort_order${1}>${2}</mt:IfAltsearchSort_order>"),
            ("mt:IfAltsearchTo\tPowerCMS[C]", "mt:IfAltsearchTo${1}>${2}</mt:IfAltsearchTo>"),
            ("mt:IfAndroid\tPowerCMS[C]", "mt:IfAndroid${1}>${2}</mt:IfAndroid>"),
            ("mt:IfAuthorCanDropBox\tPowerCMS[C]", "mt:IfAuthorCanDropBox${1}>${2}</mt:IfAuthorCanDropBox>"),
            ("mt:IfAuthorPostLimitInBlog\tPowerCMS[C]", "mt:IfAuthorPostLimitInBlog${1}>${2}</mt:IfAuthorPostLimitInBlog>"),
            ("mt:IfBannerActive\tPowerCMS[C]", "mt:IfBannerActive${1}>${2}</mt:IfBannerActive>"),
            ("mt:IfBannerHasImage\tPowerCMS[C]", "mt:IfBannerHasImage${1}>${2}</mt:IfBannerHasImage>"),
            ("mt:IfBannerHasMovie\tPowerCMS[C]", "mt:IfBannerHasMovie${1}>${2}</mt:IfBannerHasMovie>"),
            ("mt:IfBlogAttachFile\tPowerCMS[C]", "mt:IfBlogAttachFile${1}>${2}</mt:IfBlogAttachFile>"),
            ("mt:IfBlogDynamicCache\tPowerCMS[C]", "mt:IfBlogDynamicCache${1}>${2}</mt:IfBlogDynamicCache>"),
            ("mt:IfBlogDynamicConditional\tPowerCMS[C]", "mt:IfBlogDynamicConditional${1}>${2}</mt:IfBlogDynamicConditional>"),
            ("mt:IfBlogDynamicMTML\tPowerCMS[C]", "mt:IfBlogDynamicMTML${1}>${2}</mt:IfBlogDynamicMTML>"),
            ("mt:IfBlogTree\tPowerCMS[C]", "mt:IfBlogTree${1}>${2}</mt:IfBlogTree>"),
            ("mt:IfBlogTreeEntryPublished\tPowerCMS[C]", "mt:IfBlogTreeEntryPublished${1}>${2}</mt:IfBlogTreeEntryPublished>"),
            ("mt:IfBrokenImage\tPowerCMS[C]", "mt:IfBrokenImage${1}>${2}</mt:IfBrokenImage>"),
            ("mt:IfBrokenLink\tPowerCMS[C]", "mt:IfBrokenLink${1}>${2}</mt:IfBrokenLink>"),
            ("mt:IfBrokenRSS\tPowerCMS[C]", "mt:IfBrokenRSS${1}>${2}</mt:IfBrokenRSS>"),
            ("mt:IfCampaignActive\tPowerCMS[C]", "mt:IfCampaignActive${1}>${2}</mt:IfCampaignActive>"),
            ("mt:IfCampaignHasImage\tPowerCMS[C]", "mt:IfCampaignHasImage${1}>${2}</mt:IfCampaignHasImage>"),
            ("mt:IfCampaignHasMovie\tPowerCMS[C]", "mt:IfCampaignHasMovie${1}>${2}</mt:IfCampaignHasMovie>"),
            ("mt:IfCanCreateInCategory\tPowerCMS[C]", "mt:IfCanCreateInCategory${1}>${2}</mt:IfCanCreateInCategory>"),
            ("mt:IfCategoryAttachFile\tPowerCMS[C]", "mt:IfCategoryAttachFile${1}>${2}</mt:IfCategoryAttachFile>"),
            ("mt:IfCategoryIsTopLevel\tPowerCMS[C]", "mt:IfCategoryIsTopLevel${1}>${2}</mt:IfCategoryIsTopLevel>"),
            ("mt:IfChildBlog\tPowerCMS[C]", "mt:IfChildBlog${1}>${2}</mt:IfChildBlog>"),
            ("mt:IfCMS\tPowerCMS[C]", "mt:IfCMS${1}>${2}</mt:IfCMS>"),
            ("mt:IfCMSIsBlog\tPowerCMS[C]", "mt:IfCMSIsBlog${1}>${2}</mt:IfCMSIsBlog>"),
            ("mt:IfCMSParam\tPowerCMS[C]", "mt:IfCMSParam${1}>${2}</mt:IfCMSParam>"),
            ("mt:IfCMSWebSite\tPowerCMS[C]", "mt:IfCMSWebSite${1}>${2}</mt:IfCMSWebSite>"),
            ("mt:IfComponent\tPowerCMS[C]", "mt:IfComponent${1}>${2}</mt:IfComponent>"),
            ("mt:IfContactFormIsClosed\tPowerCMS[C]", "mt:IfContactFormIsClosed${1}>${2}</mt:IfContactFormIsClosed>"),
            ("mt:IfContactFormIsOpen\tPowerCMS[C]", "mt:IfContactFormIsOpen${1}>${2}</mt:IfContactFormIsOpen>"),
            ("mt:IfContactFormIsPreOpen\tPowerCMS[C]", "mt:IfContactFormIsPreOpen${1}>${2}</mt:IfContactFormIsPreOpen>"),
            ("mt:IfCurrentYear\tPowerCMS[C]", "mt:IfCurrentYear${1}>${2}</mt:IfCurrentYear>"),
            ("mt:IfEnableEdit\tPowerCMS[C]", "mt:IfEnableEdit${1}>${2}</mt:IfEnableEdit>"),
            ("mt:IfEntryAttachFile\tPowerCMS[C]", "mt:IfEntryAttachFile${1}>${2}</mt:IfEntryAttachFile>"),
            ("mt:IfEntryCanEditable\tPowerCMS[C]", "mt:IfEntryCanEditable${1}>${2}</mt:IfEntryCanEditable>"),
            ("mt:IfEntryIsDynamic\tPowerCMS[C]", "mt:IfEntryIsDynamic${1}>${2}</mt:IfEntryIsDynamic>"),
            ("mt:IfEntryIsinCategory\tPowerCMS[C]", "mt:IfEntryIsinCategory${1}>${2}</mt:IfEntryIsinCategory>"),
            ("mt:IfEntryPublished\tPowerCMS[C]", "mt:IfEntryPublished${1}>${2}</mt:IfEntryPublished>"),
            ("mt:IfEntryUnpublished\tPowerCMS[C]", "mt:IfEntryUnpublished${1}>${2}</mt:IfEntryUnpublished>"),
            ("mt:IfEstResultMatch\tPowerCMS[C]", "mt:IfEstResultMatch${1}>${2}</mt:IfEstResultMatch>"),
            ("mt:IfEstResultNext\tPowerCMS[C]", "mt:IfEstResultNext${1}>${2}</mt:IfEstResultNext>"),
            ("mt:IfEstResultPrev\tPowerCMS[C]", "mt:IfEstResultPrev${1}>${2}</mt:IfEstResultPrev>"),
            ("mt:IfExtField\tPowerCMS[C]", "mt:IfExtField${1}>${2}</mt:IfExtField>"),
            ("mt:IfExtFieldCompare\tPowerCMS[C]", "mt:IfExtFieldCompare${1}>${2}</mt:IfExtFieldCompare>"),
            ("mt:IfExtFieldFileExists\tPowerCMS[C]", "mt:IfExtFieldFileExists${1}>${2}</mt:IfExtFieldFileExists>"),
            ("mt:IfExtFieldNonEmpty\tPowerCMS[C]", "mt:IfExtFieldNonEmpty${1}>${2}</mt:IfExtFieldNonEmpty>"),
            ("mt:IfExtFieldSelected\tPowerCMS[C]", "mt:IfExtFieldSelected${1}>${2}</mt:IfExtFieldSelected>"),
            ("mt:IfExtFieldThumbnailExists\tPowerCMS[C]", "mt:IfExtFieldThumbnailExists${1}>${2}</mt:IfExtFieldThumbnailExists>"),
            ("mt:IfExtFieldType\tPowerCMS[C]", "mt:IfExtFieldType${1}>${2}</mt:IfExtFieldType>"),
            ("mt:IfExtFieldTypeImage\tPowerCMS[C]", "mt:IfExtFieldTypeImage${1}>${2}</mt:IfExtFieldTypeImage>"),
            ("mt:IfFeedbackAlreadyPosted\tPowerCMS[C]", "mt:IfFeedbackAlreadyPosted${1}>${2}</mt:IfFeedbackAlreadyPosted>"),
            ("mt:IfFormElementColumn\tPowerCMS[C]", "mt:IfFormElementColumn${1}>${2}</mt:IfFormElementColumn>"),
            ("mt:IfFormElementRequired\tPowerCMS[C]", "mt:IfFormElementRequired${1}>${2}</mt:IfFormElementRequired>"),
            ("mt:IfFormElementValidate\tPowerCMS[C]", "mt:IfFormElementValidate${1}>${2}</mt:IfFormElementValidate>"),
            ("mt:IfHyperion\tPowerCMS[C]", "mt:IfHyperion${1}>${2}</mt:IfHyperion>"),
            ("mt:IfIE\tPowerCMS[C]", "mt:IfIE${1}>${2}</mt:IfIE>"),
            ("mt:IfiPad\tPowerCMS[C]", "mt:IfiPad${1}>${2}</mt:IfiPad>"),
            ("mt:IfiPhone\tPowerCMS[C]", "mt:IfiPhone${1}>${2}</mt:IfiPhone>"),
            ("mt:IfKeitai\tPowerCMS[C]", "mt:IfKeitai${1}>${2}</mt:IfKeitai>"),
            ("mt:IfKeitaiPageCurrent\tPowerCMS[C]", "mt:IfKeitaiPageCurrent${1}>${2}</mt:IfKeitaiPageCurrent>"),
            ("mt:IfKeitaiPageNext\tPowerCMS[C]", "mt:IfKeitaiPageNext${1}>${2}</mt:IfKeitaiPageNext>"),
            ("mt:IfKeitaiPagePrev\tPowerCMS[C]", "mt:IfKeitaiPagePrev${1}>${2}</mt:IfKeitaiPagePrev>"),
            ("mt:IfMemberLogin\tPowerCMS[C]", "mt:IfMemberLogin${1}>${2}</mt:IfMemberLogin>"),
            ("mt:IfModule\tPowerCMS[C]", "mt:IfModule${1}>${2}</mt:IfModule>"),
            ("mt:IfNonSystemScope\tPowerCMS[C]", "mt:IfNonSystemScope${1}>${2}</mt:IfNonSystemScope>"),
            ("mt:IfNotSent\tPowerCMS[C]", "mt:IfNotSent${1}>${2}</mt:IfNotSent>"),
            ("mt:IfObjectGroupItemIsBlog\tPowerCMS[C]", "mt:IfObjectGroupItemIsBlog${1}>${2}</mt:IfObjectGroupItemIsBlog>"),
            ("mt:IfObjectGroupItemIsCategory\tPowerCMS[C]", "mt:IfObjectGroupItemIsCategory${1}>${2}</mt:IfObjectGroupItemIsCategory>"),
            ("mt:IfObjectGroupItemIsEntry\tPowerCMS[C]", "mt:IfObjectGroupItemIsEntry${1}>${2}</mt:IfObjectGroupItemIsEntry>"),
            ("mt:IfPagerCurrent\tPowerCMS[C]", "mt:IfPagerCurrent${1}>${2}</mt:IfPagerCurrent>"),
            ("mt:IfPagerFooter\tPowerCMS[C]", "mt:IfPagerFooter>${1}</mt:IfPagerFooter>"),
            ("mt:IfPagerHeader\tPowerCMS[C]", "mt:IfPagerHeader>${1}</mt:IfPagerHeader>"),
            ("mt:IfPagerNext\tPowerCMS[C]", "mt:IfPagerNext${1}>${2}</mt:IfPagerNext>"),
            ("mt:IfPagerPrev\tPowerCMS[C]", "mt:IfPagerPrev${1}>${2}</mt:IfPagerPrev>"),
            ("mt:IfPC\tPowerCMS[C]", "mt:IfPC${1}>${2}</mt:IfPC>"),
            ("mt:IfPerlModule\tPowerCMS[C]", "mt:IfPerlModule${1}>${2}</mt:IfPerlModule>"),
            ("mt:IfPlugin\tPowerCMS[C]", "mt:IfPlugin${1}>${2}</mt:IfPlugin>"),
            ("mt:IfPowerCMSFiles\tPowerCMS[C]", "mt:IfPowerCMSFiles${1}>${2}</mt:IfPowerCMSFiles>"),
            ("mt:IfSecure\tPowerCMS[C]", "mt:IfSecure${1}>${2}</mt:IfSecure>"),
            ("mt:IfSmartphone\tPowerCMS[C]", "mt:IfSmartphone${1}>${2}</mt:IfSmartphone>"),
            ("mt:IfTablet\tPowerCMS[C]", "mt:IfTablet${1}>${2}</mt:IfTablet>"),
            ("mt:IfTemplateSelector\tPowerCMS[C]", "mt:IfTemplateSelector${1}>${2}</mt:IfTemplateSelector>"),
            ("mt:IfTemplateSelectorBlock\tPowerCMS[C]", "mt:IfTemplateSelectorBlock${1}>${2}</mt:IfTemplateSelectorBlock>"),
            ("mt:IfTheURLFound\tPowerCMS[C]", "mt:IfTheURLFound${1}>${2}</mt:IfTheURLFound>"),
            ("mt:IfURLFound\tPowerCMS[C]", "mt:IfURLFound${1}>${2}</mt:IfURLFound>"),
            ("mt:IfUserCan\tPowerCMS[C]", "mt:IfUserCan${1}>${2}</mt:IfUserCan>"),
            ("mt:IfUserCanCreateEntry\tPowerCMS[C]", "mt:IfUserCanCreateEntry${1}>${2}</mt:IfUserCanCreateEntry>"),
            ("mt:IfUserCanCreatePage\tPowerCMS[C]", "mt:IfUserCanCreatePage${1}>${2}</mt:IfUserCanCreatePage>"),
            ("mt:IfUserHasPerm\tPowerCMS[C]", "mt:IfUserHasPerm${1}>${2}</mt:IfUserHasPerm>"),
            ("mt:IfUserIsSuperuser\tPowerCMS[C]", "mt:IfUserIsSuperuser${1}>${2}</mt:IfUserIsSuperuser>"),
            ("mt:IfUserRole\tPowerCMS[C]", "mt:IfUserRole${1}>${2}</mt:IfUserRole>"),
            ("mt:LinkIfTagged\tPowerCMS[C]", "mt:LinkIfTagged${1}>${2}</mt:LinkIfTagged>"),
            ("mt:TemplateSelector\tPowerCMS[C]", "mt:TemplateSelector${1}>${2}</mt:TemplateSelector>"),


            # Function Tag

            ("mt:AdminFullURL\tPowerCMS[F]", "mt:AdminFullURL${1} />"),
            ("mt:AltSearchAnd_or\tPowerCMS[F]", "mt:AltSearchAnd_or${1} />"),
            ("mt:AltSearchBench\tPowerCMS[F]", "mt:AltSearchBench${1} />"),
            ("mt:AltSearchBlogID\tPowerCMS[F]", "mt:AltSearchBlogID${1} />"),
            ("mt:AltSearchCategories_and_or\tPowerCMS[F]", "mt:AltSearchCategories_and_or${1} />"),
            ("mt:AltSearchCategoryID\tPowerCMS[F]", "mt:AltSearchCategoryID${1} />"),
            ("mt:AltSearchCategoryIDs\tPowerCMS[F]", "mt:AltSearchCategoryIDs${1} />"),
            ("mt:AltSearchCategoryLabel\tPowerCMS[F]", "mt:AltSearchCategoryLabel${1} />"),
            ("mt:AltSearchCurrent\tPowerCMS[F]", "mt:AltSearchCurrent${1} />"),
            ("mt:AltSearchDate\tPowerCMS[F]", "mt:AltSearchDate${1} />"),
            ("mt:AltSearchDateParams\tPowerCMS[F]", "mt:AltSearchDateParams${1} />"),
            ("mt:AltSearchFeedPath\tPowerCMS[F]", "mt:AltSearchFeedPath${1} />"),
            ("mt:AltSearchFrom\tPowerCMS[F]", "mt:AltSearchFrom${1} />"),
            ("mt:AltSearchLast\tPowerCMS[F]", "mt:AltSearchLast${1} />"),
            ("mt:AltSearchLimit\tPowerCMS[F]", "mt:AltSearchLimit${1} />"),
            ("mt:AltSearchMatch\tPowerCMS[F]", "mt:AltSearchMatch${1} />"),
            ("mt:AltSearchNext\tPowerCMS[F]", "mt:AltSearchNext${1} />"),
            ("mt:AltSearchOffset\tPowerCMS[F]", "mt:AltSearchOffset${1} />"),
            ("mt:AltSearchPageCounter\tPowerCMS[F]", "mt:AltSearchPageCounter${1} />"),
            ("mt:AltSearchPages\tPowerCMS[F]", "mt:AltSearchPages${1} />"),
            ("mt:AltSearchParam\tPowerCMS[F]", "mt:AltSearchParam${1} />"),
            ("mt:AltSearchpath\tPowerCMS[F]", "mt:AltSearchpath${1} />"),
            ("mt:AltSearchPrev\tPowerCMS[F]", "mt:AltSearchPrev${1} />"),
            ("mt:AltSearchQuery\tPowerCMS[F]", "mt:AltSearchQuery${1} />"),
            ("mt:AltSearchResultNumber\tPowerCMS[F]", "mt:AltSearchResultNumber${1} />"),
            ("mt:AltSearchResultOffset\tPowerCMS[F]", "mt:AltSearchResultOffset${1} />"),
            ("mt:AltSearchResultPermalink\tPowerCMS[F]", "mt:AltSearchResultPermalink${1} />"),
            ("mt:AltSearchSort_by\tPowerCMS[F]", "mt:AltSearchSort_by${1} />"),
            ("mt:AltSearchSort_order\tPowerCMS[F]", "mt:AltSearchSort_order${1} />"),
            ("mt:AltSearchTo\tPowerCMS[F]", "mt:AltSearchTo${1} />"),
            ("mt:AltSearchURL\tPowerCMS[F]", "mt:AltSearchURL${1} />"),
            ("mt:AssetGroupFieldScope\tPowerCMS[F]", "mt:AssetGroupFieldScope${1} />"),
            ("mt:AttachFileCounter\tPowerCMS[F]", "mt:AttachFileCounter${1} />"),
            ("mt:AuthorMobileEmail\tPowerCMS[F]", "mt:AuthorMobileEmail${1} />"),
            ("mt:AuthorMobileToken\tPowerCMS[F]", "mt:AuthorMobileToken${1} />"),
            ("mt:BannerAuthorDisplayName\tPowerCMS[F]", "mt:BannerAuthorDisplayName${1} />"),
            ("mt:BannerBannerHeight\tPowerCMS[F]", "mt:BannerBannerHeight${1} />"),
            ("mt:BannerBannerURL\tPowerCMS[F]", "mt:BannerBannerURL${1} />"),
            ("mt:BannerBannerWidth\tPowerCMS[F]", "mt:BannerBannerWidth${1} />"),
            ("mt:BannerBasename\tPowerCMS[F]", "mt:BannerBasename${1} />"),
            ("mt:BannerClicks\tPowerCMS[F]", "mt:BannerClicks${1} />"),
            ("mt:BannerConversion\tPowerCMS[F]", "mt:BannerConversion${1} />"),
            ("mt:BannerConversionCounter\tPowerCMS[F]", "mt:BannerConversionCounter${1} />"),
            ("mt:BannerConversionView\tPowerCMS[F]", "mt:BannerConversionView${1} />"),
            ("mt:BannerCounter\tPowerCMS[F]", "mt:BannerCounter${1} />"),
            ("mt:BannerCreatedOn\tPowerCMS[F]", "mt:BannerCreatedOn${1} />"),
            ("mt:BannerDisplays\tPowerCMS[F]", "mt:BannerDisplays${1} />"),
            ("mt:BannerFieldScope\tPowerCMS[F]", "mt:BannerFieldScope${1} />"),
            ("mt:BannerID\tPowerCMS[F]", "mt:BannerID${1} />"),
            ("mt:BannerMaxClicks\tPowerCMS[F]", "mt:BannerMaxClicks${1} />"),
            ("mt:BannerMaxDisplays\tPowerCMS[F]", "mt:BannerMaxDisplays${1} />"),
            ("mt:BannerMaxUniqClicks\tPowerCMS[F]", "mt:BannerMaxUniqClicks${1} />"),
            ("mt:BannerMaxUniqDisplays\tPowerCMS[F]", "mt:BannerMaxUniqDisplays${1} />"),
            ("mt:BannerMemo\tPowerCMS[F]", "mt:BannerMemo${1} />"),
            ("mt:BannerMovieURL\tPowerCMS[F]", "mt:BannerMovieURL${1} />"),
            ("mt:BannerPeriodOn\tPowerCMS[F]", "mt:BannerPeriodOn${1} />"),
            ("mt:BannerPublishingOn\tPowerCMS[F]", "mt:BannerPublishingOn${1} />"),
            ("mt:BannerRedirect\tPowerCMS[F]", "mt:BannerRedirect${1} />"),
            ("mt:BannerScript\tPowerCMS[F]", "mt:BannerScript${1} />"),
            ("mt:BannerText\tPowerCMS[F]", "mt:BannerText${1} />"),
            ("mt:BannerTitle\tPowerCMS[F]", "mt:BannerTitle${1} />"),
            ("mt:BannerUniqClicks\tPowerCMS[F]", "mt:BannerUniqClicks${1} />"),
            ("mt:BannerUniqDisplays\tPowerCMS[F]", "mt:BannerUniqDisplays${1} />"),
            ("mt:BannerURL\tPowerCMS[F]", "mt:BannerURL${1} />"),
            ("mt:BlogDynamicCache\tPowerCMS[F]", "mt:BlogDynamicCache${1} />"),
            ("mt:BlogDynamicConditional\tPowerCMS[F]", "mt:BlogDynamicConditional${1} />"),
            ("mt:BlogDynamicDirectoryIndex\tPowerCMS[F]", "mt:BlogDynamicDirectoryIndex${1} />"),
            ("mt:BlogDynamicExcludeExtension\tPowerCMS[F]", "mt:BlogDynamicExcludeExtension${1} />"),
            ("mt:BlogDynamicExtension\tPowerCMS[F]", "mt:BlogDynamicExtension${1} />"),
            ("mt:BlogDynamicMTMLCache\tPowerCMS[F]", "mt:BlogDynamicMTMLCache${1} />"),
            ("mt:BlogDynamicMTMLConditional\tPowerCMS[F]", "mt:BlogDynamicMTMLConditional${1} />"),
            ("mt:BlogDynamicSearchCache\tPowerCMS[F]", "mt:BlogDynamicSearchCache${1} />"),
            ("mt:BlogDynamicSearchCacheExpiration\tPowerCMS[F]", "mt:BlogDynamicSearchCacheExpiration${1} />"),
            ("mt:BlogDynamicSearchConditional\tPowerCMS[F]", "mt:BlogDynamicSearchConditional${1} />"),
            ("mt:BlogFilesDirective\tPowerCMS[F]", "mt:BlogFilesDirective${1} />"),
            ("mt:BlogFilesMatch\tPowerCMS[F]", "mt:BlogFilesMatch${1} />"),
            ("mt:BlogFilesMatchDirective\tPowerCMS[F]", "mt:BlogFilesMatchDirective${1} />"),
            ("mt:BlogIsMembersOnly\tPowerCMS[F]", "mt:BlogIsMembersOnly${1} />"),
            ("mt:BlogTreeBlogNameTrim\tPowerCMS[F]", "mt:BlogTreeBlogNameTrim${1} />"),
            ("mt:BlogTreeCatMaxDepth\tPowerCMS[F]", "mt:BlogTreeCatMaxDepth${1} />"),
            ("mt:BlogTreeCatMaxDisplay\tPowerCMS[F]", "mt:BlogTreeCatMaxDisplay${1} />"),
            ("mt:BlogTreeCommentCount\tPowerCMS[F]", "mt:BlogTreeCommentCount${1} />"),
            ("mt:BlogTreeDashboardCSS\tPowerCMS[F]", "mt:BlogTreeDashboardCSS${1} />"),
            ("mt:BlogTreeEntiesLastn\tPowerCMS[F]", "mt:BlogTreeEntiesLastn${1} />"),
            ("mt:BlogTreeEntriesCount\tPowerCMS[F]", "mt:BlogTreeEntriesCount${1} />"),
            ("mt:BlogTreeEntryTitleTrim\tPowerCMS[F]", "mt:BlogTreeEntryTitleTrim${1} />"),
            ("mt:BlogTreeFolderCount\tPowerCMS[F]", "mt:BlogTreeFolderCount${1} />"),
            ("mt:BlogTreeFormDataCount\tPowerCMS[F]", "mt:BlogTreeFormDataCount${1} />"),
            ("mt:BlogTreePingCount\tPowerCMS[F]", "mt:BlogTreePingCount${1} />"),
            ("mt:BlogTreeTagCount\tPowerCMS[F]", "mt:BlogTreeTagCount${1} />"),
            ("mt:BreadcrumbsLabel\tPowerCMS[F]", "mt:BreadcrumbsLabel${1} />"),
            ("mt:BreadcrumbsLink\tPowerCMS[F]", "mt:BreadcrumbsLink${1} />"),
            ("mt:BreadcrumbsTitle\tPowerCMS[F]", "mt:BreadcrumbsTitle${1} />"),
            ("mt:BreadcrumbsURL\tPowerCMS[F]", "mt:BreadcrumbsURL${1} />"),
            ("mt:CampaignAuthorDisplayName\tPowerCMS[F]", "mt:CampaignAuthorDisplayName${1} />"),
            ("mt:CampaignBannerHeight\tPowerCMS[F]", "mt:CampaignBannerHeight${1} />"),
            ("mt:CampaignBannerURL\tPowerCMS[F]", "mt:CampaignBannerURL${1} />"),
            ("mt:CampaignBannerWidth\tPowerCMS[F]", "mt:CampaignBannerWidth${1} />"),
            ("mt:CampaignBasename\tPowerCMS[F]", "mt:CampaignBasename${1} />"),
            ("mt:CampaignClicks\tPowerCMS[F]", "mt:CampaignClicks${1} />"),
            ("mt:CampaignConversion\tPowerCMS[F]", "mt:CampaignConversion${1} />"),
            ("mt:CampaignConversionCounter\tPowerCMS[F]", "mt:CampaignConversionCounter${1} />"),
            ("mt:CampaignConversionView\tPowerCMS[F]", "mt:CampaignConversionView${1} />"),
            ("mt:CampaignCounter\tPowerCMS[F]", "mt:CampaignCounter${1} />"),
            ("mt:CampaignCreatedOn\tPowerCMS[F]", "mt:CampaignCreatedOn${1} />"),
            ("mt:CampaignDisplays\tPowerCMS[F]", "mt:CampaignDisplays${1} />"),
            ("mt:CampaignFieldScope\tPowerCMS[F]", "mt:CampaignFieldScope${1} />"),
            ("mt:CampaignID\tPowerCMS[F]", "mt:CampaignID${1} />"),
            ("mt:CampaignMaxClicks\tPowerCMS[F]", "mt:CampaignMaxClicks${1} />"),
            ("mt:CampaignMaxDisplays\tPowerCMS[F]", "mt:CampaignMaxDisplays${1} />"),
            ("mt:CampaignMaxUniqClicks\tPowerCMS[F]", "mt:CampaignMaxUniqClicks${1} />"),
            ("mt:CampaignMaxUniqDisplays\tPowerCMS[F]", "mt:CampaignMaxUniqDisplays${1} />"),
            ("mt:CampaignMemo\tPowerCMS[F]", "mt:CampaignMemo${1} />"),
            ("mt:CampaignMovieURL\tPowerCMS[F]", "mt:CampaignMovieURL${1} />"),
            ("mt:CampaignPeriodOn\tPowerCMS[F]", "mt:CampaignPeriodOn${1} />"),
            ("mt:CampaignPublishingOn\tPowerCMS[F]", "mt:CampaignPublishingOn${1} />"),
            ("mt:CampaignRedirect\tPowerCMS[F]", "mt:CampaignRedirect${1} />"),
            ("mt:CampaignScript\tPowerCMS[F]", "mt:CampaignScript${1} />"),
            ("mt:CampaignText\tPowerCMS[F]", "mt:CampaignText${1} />"),
            ("mt:CampaignTitle\tPowerCMS[F]", "mt:CampaignTitle${1} />"),
            ("mt:CampaignUniqClicks\tPowerCMS[F]", "mt:CampaignUniqClicks${1} />"),
            ("mt:CampaignUniqDisplays\tPowerCMS[F]", "mt:CampaignUniqDisplays${1} />"),
            ("mt:CampaignURL\tPowerCMS[F]", "mt:CampaignURL${1} />"),
            ("mt:CategoryClass\tPowerCMS[F]", "mt:CategoryClass${1} />"),
            ("mt:CGIMaxUpload\tPowerCMS[F]", "mt:CGIMaxUpload${1} />"),
            ("mt:CMSParam\tPowerCMS[F]", "mt:CMSParam${1} />"),
            ("mt:ComponentPath\tPowerCMS[F]", "mt:ComponentPath${1} />"),
            ("mt:ContactFormAuthorDisplayName\tPowerCMS[F]", "mt:ContactFormAuthorDisplayName${1} />"),
            ("mt:ContactFormColumn\tPowerCMS[F]", "mt:ContactFormColumn${1} />"),
            ("mt:ContactFormFieldScope\tPowerCMS[F]", "mt:ContactFormFieldScope${1} />"),
            ("mt:ContactFormID\tPowerCMS[F]", "mt:ContactFormID${1} />"),
            ("mt:ContactFormName\tPowerCMS[F]", "mt:ContactFormName${1} />"),
            ("mt:ContactFormScript\tPowerCMS[F]", "mt:ContactFormScript${1} />"),
            ("mt:ContactFormStaticLink\tPowerCMS[F]", "mt:ContactFormStaticLink${1} />"),
            ("mt:CookieDump\tPowerCMS[F]", "mt:CookieDump${1} />"),
            ("mt:CountGroupCount\tPowerCMS[F]", "mt:CountGroupCount${1} />"),
            ("mt:CountGroupValue\tPowerCMS[F]", "mt:CountGroupValue${1} />"),
            ("mt:CurrentDate\tPowerCMS[F]", "mt:CurrentDate${1} />"),
            ("mt:CustomConfigAuthorDisplayName\tPowerCMS[F]", "mt:CustomConfigAuthorDisplayName${1} />"),
            ("mt:CustomConfigCreatedOn\tPowerCMS[F]", "mt:CustomConfigCreatedOn${1} />"),
            ("mt:CustomConfigID\tPowerCMS[F]", "mt:CustomConfigID${1} />"),
            ("mt:CustomConfigKey\tPowerCMS[F]", "mt:CustomConfigKey${1} />"),
            ("mt:CustomConfigModifiedOn\tPowerCMS[F]", "mt:CustomConfigModifiedOn${1} />"),
            ("mt:CustomConfigName\tPowerCMS[F]", "mt:CustomConfigName${1} />"),
            ("mt:CustomConfigPriority\tPowerCMS[F]", "mt:CustomConfigPriority${1} />"),
            ("mt:CustomConfigValue\tPowerCMS[F]", "mt:CustomConfigValue${1} />"),
            ("mt:CustomFieldColumnValue\tPowerCMS[F]", "mt:CustomFieldColumnValue${1} />"),
            ("mt:CustomFieldQuery\tPowerCMS[F]", "mt:CustomFieldQuery${1} />"),
            ("mt:CustomFieldType\tPowerCMS[F]", "mt:CustomFieldType${1} />"),
            ("mt:CustomGroupFieldScope\tPowerCMS[F]", "mt:CustomGroupFieldScope${1} />"),
            ("mt:CustomGroupName\tPowerCMS[F]", "mt:CustomGroupName${1} />"),
            ("mt:CustomGroupOrder\tPowerCMS[F]", "mt:CustomGroupOrder${1} />"),
            ("mt:CustomObjectAuthorDisplayName\tPowerCMS[F]", "mt:CustomObjectAuthorDisplayName${1} />"),
            ("mt:CustomObjectAuthoredOn\tPowerCMS[F]", "mt:CustomObjectAuthoredOn${1} />"),
            ("mt:CustomObjectBasename\tPowerCMS[F]", "mt:CustomObjectBasename${1} />"),
            ("mt:CustomObjectBlogID\tPowerCMS[F]", "mt:CustomObjectBlogID${1} />"),
            ("mt:CustomObjectBody\tPowerCMS[F]", "mt:CustomObjectBody${1} />"),
            ("mt:CustomObjectColumn\tPowerCMS[F]", "mt:CustomObjectColumn${1} />"),
            ("mt:CustomObjectColumnName\tPowerCMS[F]", "mt:CustomObjectColumnName${1} />"),
            ("mt:CustomObjectColumnValue\tPowerCMS[F]", "mt:CustomObjectColumnValue${1} />"),
            ("mt:CustomObjectCreatedOn\tPowerCMS[F]", "mt:CustomObjectCreatedOn${1} />"),
            ("mt:CustomObjectFieldScope\tPowerCMS[F]", "mt:CustomObjectFieldScope${1} />"),
            ("mt:CustomObjectFolderLink\tPowerCMS[F]", "mt:CustomObjectFolderLink${1} />"),
            ("mt:CustomObjectID\tPowerCMS[F]", "mt:CustomObjectID${1} />"),
            ("mt:CustomObjectKeywords\tPowerCMS[F]", "mt:CustomObjectKeywords${1} />"),
            ("mt:CustomObjectLabel\tPowerCMS[F]", "mt:CustomObjectLabel${1} />"),
            ("mt:CustomObjectModifiedOn\tPowerCMS[F]", "mt:CustomObjectModifiedOn${1} />"),
            ("mt:CustomObjectName\tPowerCMS[F]", "mt:CustomObjectName${1} />"),
            ("mt:CustomObjectPeriodOn\tPowerCMS[F]", "mt:CustomObjectPeriodOn${1} />"),
            ("mt:CustomObjectPermalink\tPowerCMS[F]", "mt:CustomObjectPermalink${1} />"),
            ("mt:CustomObjectsCount\tPowerCMS[F]", "mt:CustomObjectsCount${1} />"),
            ("mt:DownloadScript\tPowerCMS[F]", "mt:DownloadScript${1} />"),
            ("mt:DynamicSiteBootstrapper\tPowerCMS[F]", "mt:DynamicSiteBootstrapper${1} />"),
            ("mt:EntryAttachFile\tPowerCMS[F]", "mt:EntryAttachFile${1} />"),
            ("mt:EntryAttachFilesValues\tPowerCMS[F]", "mt:EntryAttachFilesValues${1} />"),
            ("mt:EntryChildrenCounter\tPowerCMS[F]", "mt:EntryChildrenCounter${1} />"),
            ("mt:EntryCreatorDisplayName\tPowerCMS[F]", "mt:EntryCreatorDisplayName${1} />"),
            ("mt:EntryCreatorID\tPowerCMS[F]", "mt:EntryCreatorID${1} />"),
            ("mt:EntryExtDatas\tPowerCMS[F]", "mt:EntryExtDatas${1} />"),
            ("mt:EntryFieldScope\tPowerCMS[F]", "mt:EntryFieldScope${1} />"),
            ("mt:EntryParentID\tPowerCMS[F]", "mt:EntryParentID${1} />"),
            ("mt:EntryPostCount\tPowerCMS[F]", "mt:EntryPostCount${1} />"),
            ("mt:EntryPublishedOn\tPowerCMS[F]", "mt:EntryPublishedOn${1} />"),
            ("mt:EntryStatus\tPowerCMS[F]", "mt:EntryStatus${1} />"),
            ("mt:EntryStatusNumber\tPowerCMS[F]", "mt:EntryStatusNumber${1} />"),
            ("mt:EntryTemplateName\tPowerCMS[F]", "mt:EntryTemplateName${1} />"),
            ("mt:EntryUnpublishedOn\tPowerCMS[F]", "mt:EntryUnpublishedOn${1} />"),
            ("mt:EnvDump\tPowerCMS[F]", "mt:EnvDump${1} />"),
            ("mt:Error\tPowerCMS[F]", "mt:Error${1} />"),
            ("mt:EstCmdPath\tPowerCMS[F]", "mt:EstCmdPath${1} />"),
            ("mt:EstDbPath\tPowerCMS[F]", "mt:EstDbPath${1} />"),
            ("mt:EstraierScript\tPowerCMS[F]", "mt:EstraierScript${1} />"),
            ("mt:EstResultAttribute\tPowerCMS[F]", "mt:EstResultAttribute${1} />"),
            ("mt:EstResultCount\tPowerCMS[F]", "mt:EstResultCount${1} />"),
            ("mt:EstResultDate\tPowerCMS[F]", "mt:EstResultDate${1} />"),
            ("mt:EstResultEntryBlogID\tPowerCMS[F]", "mt:EstResultEntryBlogID${1} />"),
            ("mt:EstResultEntryID\tPowerCMS[F]", "mt:EstResultEntryID${1} />"),
            ("mt:EstResultExcerpt\tPowerCMS[F]", "mt:EstResultExcerpt${1} />"),
            ("mt:EstResultTitle\tPowerCMS[F]", "mt:EstResultTitle${1} />"),
            ("mt:EstResultURL\tPowerCMS[F]", "mt:EstResultURL${1} />"),
            ("mt:ExtFieldAlt\tPowerCMS[F]", "mt:ExtFieldAlt${1} />"),
            ("mt:ExtFieldCBLabel\tPowerCMS[F]", "mt:ExtFieldCBLabel${1} />"),
            ("mt:ExtFieldCount\tPowerCMS[F]", "mt:ExtFieldCount${1} />"),
            ("mt:ExtFieldCounter\tPowerCMS[F]", "mt:ExtFieldCounter${1} />"),
            ("mt:ExtFieldDescription\tPowerCMS[F]", "mt:ExtFieldDescription${1} />"),
            ("mt:ExtFieldExportData\tPowerCMS[F]", "mt:ExtFieldExportData${1} />"),
            ("mt:ExtFieldFileDate\tPowerCMS[F]", "mt:ExtFieldFileDate${1} />"),
            ("mt:ExtFieldFileName\tPowerCMS[F]", "mt:ExtFieldFileName${1} />"),
            ("mt:ExtFieldFilePath\tPowerCMS[F]", "mt:ExtFieldFilePath${1} />"),
            ("mt:ExtFieldFileSize\tPowerCMS[F]", "mt:ExtFieldFileSize${1} />"),
            ("mt:ExtFieldFileSuffix\tPowerCMS[F]", "mt:ExtFieldFileSuffix${1} />"),
            ("mt:ExtFieldFileThumbnail\tPowerCMS[F]", "mt:ExtFieldFileThumbnail${1} />"),
            ("mt:ExtFieldID\tPowerCMS[F]", "mt:ExtFieldID${1} />"),
            ("mt:ExtFieldImageHeight\tPowerCMS[F]", "mt:ExtFieldImageHeight${1} />"),
            ("mt:ExtFieldImageWidth\tPowerCMS[F]", "mt:ExtFieldImageWidth${1} />"),
            ("mt:ExtFieldLabel\tPowerCMS[F]", "mt:ExtFieldLabel${1} />"),
            ("mt:ExtFieldMultiValue\tPowerCMS[F]", "mt:ExtFieldMultiValue${1} />"),
            ("mt:ExtFieldName\tPowerCMS[F]", "mt:ExtFieldName${1} />"),
            ("mt:ExtFieldNum\tPowerCMS[F]", "mt:ExtFieldNum${1} />"),
            ("mt:ExtFieldText\tPowerCMS[F]", "mt:ExtFieldText${1} />"),
            ("mt:ExtFieldThumbnail\tPowerCMS[F]", "mt:ExtFieldThumbnail${1} />"),
            ("mt:ExtFieldThumbnailHeight\tPowerCMS[F]", "mt:ExtFieldThumbnailHeight${1} />"),
            ("mt:ExtFieldThumbnailWidth\tPowerCMS[F]", "mt:ExtFieldThumbnailWidth${1} />"),
            ("mt:ExtFieldValue\tPowerCMS[F]", "mt:ExtFieldValue${1} />"),
            ("mt:FeedbackClosedMessage\tPowerCMS[F]", "mt:FeedbackClosedMessage${1} />"),
            ("mt:FeedbackConfirmMessage\tPowerCMS[F]", "mt:FeedbackConfirmMessage${1} />"),
            ("mt:FeedbackCount\tPowerCMS[F]", "mt:FeedbackCount${1} />"),
            ("mt:FeedbackErrorMessage\tPowerCMS[F]", "mt:FeedbackErrorMessage${1} />"),
            ("mt:FeedbackInformationMessage\tPowerCMS[F]", "mt:FeedbackInformationMessage${1} />"),
            ("mt:FeedbackPreOpenMessage\tPowerCMS[F]", "mt:FeedbackPreOpenMessage${1} />"),
            ("mt:FeedbackThanksMessage\tPowerCMS[F]", "mt:FeedbackThanksMessage${1} />"),
            ("mt:FileGetContents\tPowerCMS[F]", "mt:FileGetContents${1} />"),
            ("mt:FormCMSFormStatusMsg\tPowerCMS[F]", "mt:FormCMSFormStatusMsg${1} />"),
            ("mt:FormCMSHTML\tPowerCMS[F]", "mt:FormCMSHTML${1} />"),
            ("mt:FormElementBasename\tPowerCMS[F]", "mt:FormElementBasename${1} />"),
            ("mt:FormElementColumn\tPowerCMS[F]", "mt:FormElementColumn${1} />"),
            ("mt:FormElementDefault\tPowerCMS[F]", "mt:FormElementDefault${1} />"),
            ("mt:FormElementDescription\tPowerCMS[F]", "mt:FormElementDescription${1} />"),
            ("mt:FormElementHTML\tPowerCMS[F]", "mt:FormElementHTML${1} />"),
            ("mt:FormElementName\tPowerCMS[F]", "mt:FormElementName${1} />"),
            ("mt:FormElementOption\tPowerCMS[F]", "mt:FormElementOption${1} />"),
            ("mt:FormElementSize\tPowerCMS[F]", "mt:FormElementSize${1} />"),
            ("mt:FormElementType\tPowerCMS[F]", "mt:FormElementType${1} />"),
            ("mt:FormScript\tPowerCMS[F]", "mt:FormScript${1} />"),
            ("mt:GAHotEntriesCount\tPowerCMS[F]", "mt:GAHotEntriesCount${1} />"),
            ("mt:GALastUpdateTs\tPowerCMS[F]", "mt:GALastUpdateTs${1} />"),
            ("mt:GATrackingCode\tPowerCMS[F]", "mt:GATrackingCode${1} />"),
            ("mt:GetCareer\tPowerCMS[F]", "mt:GetCareer${1} />"),
            ("mt:GetCookie\tPowerCMS[F]", "mt:GetCookie${1} />"),
            ("mt:GetEmoji\tPowerCMS[F]", "mt:GetEmoji${1} />"),
            ("mt:GetEmojiLegacy\tPowerCMS[F]", "mt:GetEmojiLegacy${1} />"),
            ("mt:GetEmojiRegacy\tPowerCMS[F]", "mt:GetEmojiRegacy${1} />"),
            ("mt:GetEmojiUnicode\tPowerCMS[F]", "mt:GetEmojiUnicode${1} />"),
            ("mt:GetEmoticon\tPowerCMS[F]", "mt:GetEmoticon${1} />"),
            ("mt:GetEnv\tPowerCMS[F]", "mt:GetEnv${1} />"),
            ("mt:GetObjectChildLabel\tPowerCMS[F]", "mt:GetObjectChildLabel${1} />"),
            ("mt:GetObjectClassLabel\tPowerCMS[F]", "mt:GetObjectClassLabel${1} />"),
            ("mt:GetUnicodeEmoji\tPowerCMS[F]", "mt:GetUnicodeEmoji${1} />"),
            ("mt:ImgAltCheckAlertCount\tPowerCMS[F]", "mt:ImgAltCheckAlertCount${1} />"),
            ("mt:ImgAltCheckErrorCode\tPowerCMS[F]", "mt:ImgAltCheckErrorCode${1} />"),
            ("mt:ImgAltCheckErrorCount\tPowerCMS[F]", "mt:ImgAltCheckErrorCount${1} />"),
            ("mt:ImgAltCheckErrorMessage\tPowerCMS[F]", "mt:ImgAltCheckErrorMessage${1} />"),
            ("mt:ImgAltCheckFilename\tPowerCMS[F]", "mt:ImgAltCheckFilename${1} />"),
            ("mt:ImgAltCheckImgAlt\tPowerCMS[F]", "mt:ImgAltCheckImgAlt${1} />"),
            ("mt:ImgAltCheckImgSrc\tPowerCMS[F]", "mt:ImgAltCheckImgSrc${1} />"),
            ("mt:ISCreatePosts\tPowerCMS[F]", "mt:ISCreatePosts${1} />"),
            ("mt:ItemGroupBlogsCount\tPowerCMS[F]", "mt:ItemGroupBlogsCount${1} />"),
            ("mt:ItemGroupCategoriesCount\tPowerCMS[F]", "mt:ItemGroupCategoriesCount${1} />"),
            ("mt:ItemGroupEntriesCount\tPowerCMS[F]", "mt:ItemGroupEntriesCount${1} />"),
            ("mt:KeitaiEmoticonSize\tPowerCMS[F]", "mt:KeitaiEmoticonSize${1} />"),
            ("mt:KeitaiPageCount\tPowerCMS[F]", "mt:KeitaiPageCount${1} />"),
            ("mt:KeitaiPageLink\tPowerCMS[F]", "mt:KeitaiPageLink${1} />"),
            ("mt:KeitaiPageNextLink\tPowerCMS[F]", "mt:KeitaiPageNextLink${1} />"),
            ("mt:KeitaiPageNumber\tPowerCMS[F]", "mt:KeitaiPageNumber${1} />"),
            ("mt:KeitaiPagePrevLink\tPowerCMS[F]", "mt:KeitaiPagePrevLink${1} />"),
            ("mt:LatestRevisionValue\tPowerCMS[F]", "mt:LatestRevisionValue${1} />"),
            ("mt:LinkAuthorDisplayName\tPowerCMS[F]", "mt:LinkAuthorDisplayName${1} />"),
            ("mt:LinkAuthoredOn\tPowerCMS[F]", "mt:LinkAuthoredOn${1} />"),
            ("mt:LinkBlogID\tPowerCMS[F]", "mt:LinkBlogID${1} />"),
            ("mt:LinkCreatedOn\tPowerCMS[F]", "mt:LinkCreatedOn${1} />"),
            ("mt:LinkDescription\tPowerCMS[F]", "mt:LinkDescription${1} />"),
            ("mt:LinkFieldScope\tPowerCMS[F]", "mt:LinkFieldScope${1} />"),
            ("mt:LinkHTML\tPowerCMS[F]", "mt:LinkHTML${1} />"),
            ("mt:LinkImageAddress\tPowerCMS[F]", "mt:LinkImageAddress${1} />"),
            ("mt:LinkModifiedOn\tPowerCMS[F]", "mt:LinkModifiedOn${1} />"),
            ("mt:LinkName\tPowerCMS[F]", "mt:LinkName${1} />"),
            ("mt:LinkNotes\tPowerCMS[F]", "mt:LinkNotes${1} />"),
            ("mt:LinkRating\tPowerCMS[F]", "mt:LinkRating${1} />"),
            ("mt:LinkRel\tPowerCMS[F]", "mt:LinkRel${1} />"),
            ("mt:LinkRSSAddress\tPowerCMS[F]", "mt:LinkRSSAddress${1} />"),
            ("mt:LinkRSSUpdatedOn\tPowerCMS[F]", "mt:LinkRSSUpdatedOn${1} />"),
            ("mt:LinkTarget\tPowerCMS[F]", "mt:LinkTarget${1} />"),
            ("mt:LinkTitle\tPowerCMS[F]", "mt:LinkTitle${1} />"),
            ("mt:LinkURL\tPowerCMS[F]", "mt:LinkURL${1} />"),
            ("mt:LinkURLUpdatedOn\tPowerCMS[F]", "mt:LinkURLUpdatedOn${1} />"),
            ("mt:MailMagazineNumber\tPowerCMS[F]", "mt:MailMagazineNumber${1} />"),
            ("mt:MembersLoginCheck\tPowerCMS[F]", "mt:MembersLoginCheck${1} />"),
            ("mt:MembersScript\tPowerCMS[F]", "mt:MembersScript${1} />"),
            ("mt:ObjectGroupItemClass\tPowerCMS[F]", "mt:ObjectGroupItemClass${1} />"),
            ("mt:PageFieldScope\tPowerCMS[F]", "mt:PageFieldScope${1} />"),
            ("mt:PagePostCount\tPowerCMS[F]", "mt:PagePostCount${1} />"),
            ("mt:PagerCounter\tPowerCMS[F]", "mt:PagerCounter${1} />"),
            ("mt:PagerCurrent\tPowerCMS[F]", "mt:PagerCurrent${1} />"),
            ("mt:PagerLink\tPowerCMS[F]", "mt:PagerLink${1} />"),
            ("mt:PagerNextLink\tPowerCMS[F]", "mt:PagerNextLink${1} />"),
            ("mt:PagerPrevLink\tPowerCMS[F]", "mt:PagerPrevLink${1} />"),
            ("mt:PagerTotal\tPowerCMS[F]", "mt:PagerTotal${1} />"),
            ("mt:Permalink\tPowerCMS[F]", "mt:Permalink${1} />"),
            ("mt:PluginPath\tPowerCMS[F]", "mt:PluginPath${1} />"),
            ("mt:PluginSetting\tPowerCMS[F]", "mt:PluginSetting${1} />"),
            ("mt:PluginVersion\tPowerCMS[F]", "mt:PluginVersion${1} />"),
            ("mt:PostFieldsAsStr\tPowerCMS[F]", "mt:PostFieldsAsStr${1} />"),
            ("mt:PowerCMSEdition\tPowerCMS[F]", "mt:PowerCMSEdition${1} />"),
            ("mt:PowerCMSFilesDir\tPowerCMS[F]", "mt:PowerCMSFilesDir${1} />"),
            ("mt:PowerCMSVersion\tPowerCMS[F]", "mt:PowerCMSVersion${1} />"),
            ("mt:QueryDump\tPowerCMS[F]", "mt:QueryDump${1} />"),
            ("mt:RebuildBlog\tPowerCMS[F]", "mt:RebuildBlog${1} />"),
            ("mt:RebuildIndexByBlogId\tPowerCMS[F]", "mt:RebuildIndexByBlogId${1} />"),
            ("mt:RebuildIndexById\tPowerCMS[F]", "mt:RebuildIndexById${1} />"),
            ("mt:RevisionCount\tPowerCMS[F]", "mt:RevisionCount${1} />"),
            ("mt:SidebarAssetCount\tPowerCMS[F]", "mt:SidebarAssetCount${1} />"),
            ("mt:StaticFullURL\tPowerCMS[F]", "mt:StaticFullURL${1} />"),
            ("mt:TableColumnValue\tPowerCMS[F]", "mt:TableColumnValue${1} />"),
            ("mt:TabSplitLine\tPowerCMS[F]", "mt:TabSplitLine${1} />"),
            ("mt:TemplateGroupFieldScope\tPowerCMS[F]", "mt:TemplateGroupFieldScope${1} />"),
            ("mt:TemplateName\tPowerCMS[F]", "mt:TemplateName${1} />"),
            ("mt:TemplateOutput\tPowerCMS[F]", "mt:TemplateOutput${1} />"),
            ("mt:TemplateText\tPowerCMS[F]", "mt:TemplateText${1} />"),
            ("mt:ThisURL\tPowerCMS[F]", "mt:ThisURL${1} />"),
            ("mt:VarDump\tPowerCMS[F]", "mt:VarDump${1} />"),
            ("mt:ViewerScript\tPowerCMS[F]", "mt:ViewerScript${1} />"),
            ("mt:XMLDocument\tPowerCMS[F]", "mt:XMLDocument${1} />"),
            ("mt:Year\tPowerCMS[F]", "mt:Year${1} />")


        ], sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS)
