import sublime, sublime_plugin
import re
def match(rex, str):
    m = rex.match(str)
    if m:
        return m.group(0)
    else:
        return None
class PowerModifierCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        # if not view.match_selector(locations[0],
        #         "text.html - source"):
        #     return []
        pt = locations[0] - len(prefix) - 1
        ch = view.substr(sublime.Region(pt, pt + 1))
        if ch != ' ':
            return []
        return ([
            ("absolute=\"\"\tPowerCMS[M]", "absolute=\"${1}\""),
            ("abs_addslash=\"\"\tPowerCMS[M]", "abs_addslash=\"${1}\""),
            ("accessibility=\"\"\tPowerCMS[M]", "accessibility=\"${1}\""),
            ("add_session_for_mobile=\"\"\tPowerCMS[M]", "add_session_for_mobile=\"${1}\""),
            ("asset2url=\"\"\tPowerCMS[M]", "asset2url=\"${1}\""),
            ("asset_id=\"\"\tPowerCMS[M]", "asset_id=\"${1}\""),
            ("build_mtml=\"\"\tPowerCMS[M]", "build_mtml=\"${1}\""),
            ("convert2thumbnail=\"\"\tPowerCMS[M]", "convert2thumbnail=\"${1}\""),
            ("convertthumbnail=\"\"\tPowerCMS[M]", "convertthumbnail=\"${1}\""),
            ("cut_firstslash=\"\"\tPowerCMS[M]", "cut_firstslash=\"${1}\""),
            ("emoticon2mtml=\"\"\tPowerCMS[M]", "emoticon2mtml=\"${1}\""),
            ("exportformat=\"\"\tPowerCMS[M]", "exportformat=\"${1}\""),
            ("external_link_for_mobile=\"\"\tPowerCMS[M]", "external_link_for_mobile=\"${1}\""),
            ("format_ts=\"\"\tPowerCMS[M]", "format_ts=\"${1}\""),
            ("get_basename=\"\"\tPowerCMS[M]", "get_basename=\"${1}\""),
            ("highlight=\"\"\tPowerCMS[M]", "highlight=\"${1}\""),
            ("hilight=\"\"\tPowerCMS[M]", "hilight=\"${1}\""),
            ("HTMLImageElement=\"\"\tPowerCMS[M]", "HTMLImageElement=\"${1}\""),
            ("is_draft=\"\"\tPowerCMS[M]", "is_draft=\"${1}\""),
            ("path2url=\"\"\tPowerCMS[M]", "path2url=\"${1}\""),
            ("pickup_extension=\"\"\tPowerCMS[M]", "pickup_extension=\"${1}\""),
            ("set_loop=\"\"\tPowerCMS[M]", "set_loop=\"${1}\""),
            ("str2keitai=\"\"\tPowerCMS[M]", "str2keitai=\"${1}\""),
            ("strip_emptylines=\"\"\tPowerCMS[M]", "strip_emptylines=\"${1}\""),
            ("tab2table=\"\"\tPowerCMS[M]", "tab2table=\"${1}\""),
            ("table2tag=\"\"\tPowerCMS[M]", "table2tag=\"${1}\""),
            ("tel2link=\"\"\tPowerCMS[M]", "tel2link=\"${1}\""),
            ("translate_templatized=\"\"\tPowerCMS[M]", "translate_templatized=\"${1}\""),
            ("trimj_to=\"\"\tPowerCMS[M]", "trimj_to=\"${1}\""),
            ("url2download=\"\"\tPowerCMS[M]", "url2download=\"${1}\""),
            ("z2h=\"\"\tPowerCMS[M]", "z2h=\"${1}\"")
        ], sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS)
class PowerMTTagCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        # if not view.match_selector(locations[0],
        #         "text.html - source"):
        #     return []
        pt = locations[0] - len(prefix) - 1
        ch = view.substr(sublime.Region(pt, pt + 1))
        if ch != '<':
            return []
        function_tag_type = view.settings().get('mtml_function_tag_type')
        if function_tag_type == 'dollar':
            tag_open = '\$'
            tag_close = '\$>'
        elif function_tag_type == 'none':
            tag_open = ''
            tag_close = '>'
        else:
            tag_open = ''
            tag_close = ' />'
        # block_tag_break = view.settings().get('mtml_block_tag_break')
        # if block_tag_break:
        #     tag_break = '\n\n'
        # else:
        #     tag_break = ''
        mt_prefix = view.settings().get('mtml_prefix')
        if mt_prefix:
            mt_prefix = view.settings().get('mtml_prefix')
        else:
            mt_prefix = 'mt:'
        return ([
            # Block Tag
            (mt_prefix + "AccessibleBlock\tPowerCMS[B]", mt_prefix + "AccessibleBlock${1}>${2}</" + mt_prefix + "AccessibleBlock>"),
            (mt_prefix + "AccessibleBlock\tPowerCMS[B]", mt_prefix + "AccessibleBlock${1}>${2}</" + mt_prefix + "AccessibleBlock>"),
            (mt_prefix + "AltSearchMetadata\tPowerCMS[B]", mt_prefix + "AltSearchMetadata${1}>${2}</" + mt_prefix + "AltSearchMetadata>"),
            (mt_prefix + "AltSearchMetadatas\tPowerCMS[B]", mt_prefix + "AltSearchMetadatas${1}>${2}</" + mt_prefix + "AltSearchMetadatas>"),
            (mt_prefix + "AltSearchResults\tPowerCMS[B]", mt_prefix + "AltSearchResults${1}>${2}</" + mt_prefix + "AltSearchResults>"),
            (mt_prefix + "Banner\tPowerCMS[B]", mt_prefix + "Banner${1}>${2}</" + mt_prefix + "Banner>"),
            (mt_prefix + "BannerAsset\tPowerCMS[B]", mt_prefix + "BannerAsset${1}>${2}</" + mt_prefix + "BannerAsset>"),
            (mt_prefix + "BannerAuthor\tPowerCMS[B]", mt_prefix + "BannerAuthor${1}>${2}</" + mt_prefix + "BannerAuthor>"),
            (mt_prefix + "BannerRandom\tPowerCMS[B]", mt_prefix + "BannerRandom${1}>${2}</" + mt_prefix + "BannerRandom>"),
            (mt_prefix + "Banners\tPowerCMS[B]", mt_prefix + "Banners${1}>${2}</" + mt_prefix + "Banners>"),
            (mt_prefix + "BannersFooter\tPowerCMS[B]", mt_prefix + "BannersFooter>${1}</" + mt_prefix + "BannersFooter>"),
            (mt_prefix + "BannersHeader\tPowerCMS[B]", mt_prefix + "BannersHeader>${1}</" + mt_prefix + "BannersHeader>"),
            (mt_prefix + "BannerTags\tPowerCMS[B]", mt_prefix + "BannerTags${1}>${2}</" + mt_prefix + "BannerTags>"),
            (mt_prefix + "BlogAttachFiles\tPowerCMS[B]", mt_prefix + "BlogAttachFiles${1}>${2}</" + mt_prefix + "BlogAttachFiles>"),
            (mt_prefix + "BlogTreeAssets\tPowerCMS[B]", mt_prefix + "BlogTreeAssets${1}>${2}</" + mt_prefix + "BlogTreeAssets>"),
            (mt_prefix + "BlogTreeAssetsFooter\tPowerCMS[B]", mt_prefix + "BlogTreeAssetsFooter>${1}</" + mt_prefix + "BlogTreeAssetsFooter>"),
            (mt_prefix + "BlogTreeAssetsHeader\tPowerCMS[B]", mt_prefix + "BlogTreeAssetsHeader>${1}</" + mt_prefix + "BlogTreeAssetsHeader>"),
            (mt_prefix + "BlogTreeEntries\tPowerCMS[B]", mt_prefix + "BlogTreeEntries${1}>${2}</" + mt_prefix + "BlogTreeEntries>"),
            (mt_prefix + "BlogTreeEntriesFooter\tPowerCMS[B]", mt_prefix + "BlogTreeEntriesFooter>${1}</" + mt_prefix + "BlogTreeEntriesFooter>"),
            (mt_prefix + "BlogTreeEntriesHeader\tPowerCMS[B]", mt_prefix + "BlogTreeEntriesHeader>${1}</" + mt_prefix + "BlogTreeEntriesHeader>"),
            (mt_prefix + "Breadcrumbs\tPowerCMS[B]", mt_prefix + "Breadcrumbs${1}>${2}</" + mt_prefix + "Breadcrumbs>"),
            (mt_prefix + "Campaign\tPowerCMS[B]", mt_prefix + "Campaign${1}>${2}</" + mt_prefix + "Campaign>"),
            (mt_prefix + "CampaignAsset\tPowerCMS[B]", mt_prefix + "CampaignAsset${1}>${2}</" + mt_prefix + "CampaignAsset>"),
            (mt_prefix + "CampaignAuthor\tPowerCMS[B]", mt_prefix + "CampaignAuthor${1}>${2}</" + mt_prefix + "CampaignAuthor>"),
            (mt_prefix + "CampaignRandom\tPowerCMS[B]", mt_prefix + "CampaignRandom${1}>${2}</" + mt_prefix + "CampaignRandom>"),
            (mt_prefix + "Campaigns\tPowerCMS[B]", mt_prefix + "Campaigns${1}>${2}</" + mt_prefix + "Campaigns>"),
            (mt_prefix + "CampaignsFooter\tPowerCMS[B]", mt_prefix + "CampaignsFooter>${1}</" + mt_prefix + "CampaignsFooter>"),
            (mt_prefix + "CampaignsHeader\tPowerCMS[B]", mt_prefix + "CampaignsHeader>${1}</" + mt_prefix + "CampaignsHeader>"),
            (mt_prefix + "CampaignTags\tPowerCMS[B]", mt_prefix + "CampaignTags${1}>${2}</" + mt_prefix + "CampaignTags>"),
            (mt_prefix + "CategoryAttachFiles\tPowerCMS[B]", mt_prefix + "CategoryAttachFiles${1}>${2}</" + mt_prefix + "CategoryAttachFiles>"),
            (mt_prefix + "CfEntrySetContext\tPowerCMS[B]", mt_prefix + "CfEntrySetContext${1}>${2}</" + mt_prefix + "CfEntrySetContext>"),
            (mt_prefix + "CMSBlogContext\tPowerCMS[B]", mt_prefix + "CMSBlogContext${1}>${2}</" + mt_prefix + "CMSBlogContext>"),
            (mt_prefix + "CMSCacheBlock\tPowerCMS[B]", mt_prefix + "CMSCacheBlock${1}>${2}</" + mt_prefix + "CMSCacheBlock>"),
            (mt_prefix + "CMSContext\tPowerCMS[B]", mt_prefix + "CMSContext${1}>${2}</" + mt_prefix + "CMSContext>"),
            (mt_prefix + "ContactFormFileAsset\tPowerCMS[B]", mt_prefix + "ContactFormFileAsset${1}>${2}</" + mt_prefix + "ContactFormFileAsset>"),
            (mt_prefix + "ContactForms\tPowerCMS[B]", mt_prefix + "ContactForms${1}>${2}</" + mt_prefix + "ContactForms>"),
            (mt_prefix + "ConvertSJIS\tPowerCMS[B]", mt_prefix + "ConvertSJIS${1}>${2}</" + mt_prefix + "ConvertSJIS>"),
            (mt_prefix + "CountGroupBy\tPowerCMS[B]", mt_prefix + "CountGroupBy${1}>${2}</" + mt_prefix + "CountGroupBy>"),
            (mt_prefix + "CSSCompressor\tPowerCMS[B]", mt_prefix + "CSSCompressor${1}>${2}</" + mt_prefix + "CSSCompressor>"),
            (mt_prefix + "CustomConfig\tPowerCMS[B]", mt_prefix + "CustomConfig${1}>${2}</" + mt_prefix + "CustomConfig>"),
            (mt_prefix + "CustomConfigLoop\tPowerCMS[B]", mt_prefix + "CustomConfigLoop${1}>${2}</" + mt_prefix + "CustomConfigLoop>"),
            (mt_prefix + "CustomGroups\tPowerCMS[B]", mt_prefix + "CustomGroups${1}>${2}</" + mt_prefix + "CustomGroups>"),
            (mt_prefix + "CustomGroupsFooter\tPowerCMS[B]", mt_prefix + "CustomGroupsFooter>${1}</" + mt_prefix + "CustomGroupsFooter>"),
            (mt_prefix + "CustomGroupsHeader\tPowerCMS[B]", mt_prefix + "CustomGroupsHeader>${1}</" + mt_prefix + "CustomGroupsHeader>"),
            (mt_prefix + "CustomObject\tPowerCMS[B]", mt_prefix + "CustomObject${1}>${2}</" + mt_prefix + "CustomObject>"),
            (mt_prefix + "CustomObjectAuthor\tPowerCMS[B]", mt_prefix + "CustomObjectAuthor${1}>${2}</" + mt_prefix + "CustomObjectAuthor>"),
            (mt_prefix + "CustomObjectColumns\tPowerCMS[B]", mt_prefix + "CustomObjectColumns${1}>${2}</" + mt_prefix + "CustomObjectColumns>"),
            (mt_prefix + "CustomObjectColumnsFooter\tPowerCMS[B]", mt_prefix + "CustomObjectColumnsFooter>${1}</" + mt_prefix + "CustomObjectColumnsFooter>"),
            (mt_prefix + "CustomObjectColumnsHeader\tPowerCMS[B]", mt_prefix + "CustomObjectColumnsHeader>${1}</" + mt_prefix + "CustomObjectColumnsHeader>"),
            (mt_prefix + "CustomObjectFolder\tPowerCMS[B]", mt_prefix + "CustomObjectFolder${1}>${2}</" + mt_prefix + "CustomObjectFolder>"),
            (mt_prefix + "CustomObjects\tPowerCMS[B]", mt_prefix + "CustomObjects${1}>${2}</" + mt_prefix + "CustomObjects>"),
            (mt_prefix + "CustomObjectsFooter\tPowerCMS[B]", mt_prefix + "CustomObjectsFooter>${1}</" + mt_prefix + "CustomObjectsFooter>"),
            (mt_prefix + "CustomObjectsHeader\tPowerCMS[B]", mt_prefix + "CustomObjectsHeader>${1}</" + mt_prefix + "CustomObjectsHeader>"),
            (mt_prefix + "CustomObjectTags\tPowerCMS[B]", mt_prefix + "CustomObjectTags${1}>${2}</" + mt_prefix + "CustomObjectTags>"),
            (mt_prefix + "Emoticon2emoji\tPowerCMS[B]", mt_prefix + "Emoticon2emoji${1}>${2}</" + mt_prefix + "Emoticon2emoji>"),
            (mt_prefix + "EntryAttachFiles\tPowerCMS[B]", mt_prefix + "EntryAttachFiles${1}>${2}</" + mt_prefix + "EntryAttachFiles>"),
            (mt_prefix + "EntryChildrenNext\tPowerCMS[B]", mt_prefix + "EntryChildrenNext${1}>${2}</" + mt_prefix + "EntryChildrenNext>"),
            (mt_prefix + "EntryChildrenPages\tPowerCMS[B]", mt_prefix + "EntryChildrenPages${1}>${2}</" + mt_prefix + "EntryChildrenPages>"),
            (mt_prefix + "EntryChildrenPagesFooter\tPowerCMS[B]", mt_prefix + "EntryChildrenPagesFooter>${1}</" + mt_prefix + "EntryChildrenPagesFooter>"),
            (mt_prefix + "EntryChildrenPagesHeader\tPowerCMS[B]", mt_prefix + "EntryChildrenPagesHeader>${1}</" + mt_prefix + "EntryChildrenPagesHeader>"),
            (mt_prefix + "EntryChildrenPrev\tPowerCMS[B]", mt_prefix + "EntryChildrenPrev${1}>${2}</" + mt_prefix + "EntryChildrenPrev>"),
            (mt_prefix + "EntryCreatorContext\tPowerCMS[B]", mt_prefix + "EntryCreatorContext${1}>${2}</" + mt_prefix + "EntryCreatorContext>"),
            (mt_prefix + "EntryPosts\tPowerCMS[B]", mt_prefix + "EntryPosts${1}>${2}</" + mt_prefix + "EntryPosts>"),
            (mt_prefix + "EstraierBlock\tPowerCMS[B]", mt_prefix + "EstraierBlock${1}>${2}</" + mt_prefix + "EstraierBlock>"),
            (mt_prefix + "EstraierMeta\tPowerCMS[B]", mt_prefix + "EstraierMeta${1}>${2}</" + mt_prefix + "EstraierMeta>"),
            (mt_prefix + "EstraierResults\tPowerCMS[B]", mt_prefix + "EstraierResults${1}>${2}</" + mt_prefix + "EstraierResults>"),
            (mt_prefix + "EstraierSuffix\tPowerCMS[B]", mt_prefix + "EstraierSuffix${1}>${2}</" + mt_prefix + "EstraierSuffix>"),
            (mt_prefix + "EstraierTarget\tPowerCMS[B]", mt_prefix + "EstraierTarget${1}>${2}</" + mt_prefix + "EstraierTarget>"),
            (mt_prefix + "EstResultBlogCtx\tPowerCMS[B]", mt_prefix + "EstResultBlogCtx${1}>${2}</" + mt_prefix + "EstResultBlogCtx>"),
            (mt_prefix + "EstResultEntryCtx\tPowerCMS[B]", mt_prefix + "EstResultEntryCtx${1}>${2}</" + mt_prefix + "EstResultEntryCtx>"),
            (mt_prefix + "EstResultFooter\tPowerCMS[B]", mt_prefix + "EstResultFooter>${1}</" + mt_prefix + "EstResultFooter>"),
            (mt_prefix + "EstResultHeader\tPowerCMS[B]", mt_prefix + "EstResultHeader>${1}</" + mt_prefix + "EstResultHeader>"),
            (mt_prefix + "EstResultPager\tPowerCMS[B]", mt_prefix + "EstResultPager${1}>${2}</" + mt_prefix + "EstResultPager>"),
            (mt_prefix + "EstResultPagerFooter\tPowerCMS[B]", mt_prefix + "EstResultPagerFooter>${1}</" + mt_prefix + "EstResultPagerFooter>"),
            (mt_prefix + "EstResultPagerHeader\tPowerCMS[B]", mt_prefix + "EstResultPagerHeader>${1}</" + mt_prefix + "EstResultPagerHeader>"),
            (mt_prefix + "ExportEntries\tPowerCMS[B]", mt_prefix + "ExportEntries${1}>${2}</" + mt_prefix + "ExportEntries>"),
            (mt_prefix + "ExtFieldAsset\tPowerCMS[B]", mt_prefix + "ExtFieldAsset${1}>${2}</" + mt_prefix + "ExtFieldAsset>"),
            (mt_prefix + "ExtFields\tPowerCMS[B]", mt_prefix + "ExtFields${1}>${2}</" + mt_prefix + "ExtFields>"),
            (mt_prefix + "ExtFieldsMultiValues\tPowerCMS[B]", mt_prefix + "ExtFieldsMultiValues${1}>${2}</" + mt_prefix + "ExtFieldsMultiValues>"),
            (mt_prefix + "FormElementOptions\tPowerCMS[B]", mt_prefix + "FormElementOptions${1}>${2}</" + mt_prefix + "FormElementOptions>"),
            (mt_prefix + "GAHotEntries\tPowerCMS[B]", mt_prefix + "GAHotEntries${1}>${2}</" + mt_prefix + "GAHotEntries>"),
            (mt_prefix + "GroupAssets\tPowerCMS[B]", mt_prefix + "GroupAssets${1}>${2}</" + mt_prefix + "GroupAssets>"),
            (mt_prefix + "GroupAssetsFooter\tPowerCMS[B]", mt_prefix + "GroupAssetsFooter>${1}</" + mt_prefix + "GroupAssetsFooter>"),
            (mt_prefix + "GroupAssetsHeader\tPowerCMS[B]", mt_prefix + "GroupAssetsHeader>${1}</" + mt_prefix + "GroupAssetsHeader>"),
            (mt_prefix + "GroupBlogs\tPowerCMS[B]", mt_prefix + "GroupBlogs${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</" + mt_prefix + "GroupBlogs>"),
            (mt_prefix + "GroupBlogsFooter\tPowerCMS[B]", mt_prefix + "GroupBlogsFooter>${1}</" + mt_prefix + "GroupBlogsFooter>"),
            (mt_prefix + "GroupBlogsHeader\tPowerCMS[B]", mt_prefix + "GroupBlogsHeader>${1}</" + mt_prefix + "GroupBlogsHeader>"),
            (mt_prefix + "GroupBlogsWebsites\tPowerCMS[B]", mt_prefix + "GroupBlogsWebsites${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</" + mt_prefix + "GroupBlogsWebsites>"),
            (mt_prefix + "GroupBlogsWebsitesFooter\tPowerCMS[B]", mt_prefix + "GroupBlogsWebsitesFooter>${1}</" + mt_prefix + "GroupBlogsWebsitesFooter>"),
            (mt_prefix + "GroupBlogsWebsitesHeader\tPowerCMS[B]", mt_prefix + "GroupBlogsWebsitesHeader>${1}</" + mt_prefix + "GroupBlogsWebsitesHeader>"),
            (mt_prefix + "GroupCategories\tPowerCMS[B]", mt_prefix + "GroupCategories${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</" + mt_prefix + "GroupCategories>"),
            (mt_prefix + "GroupCategoriesFolders\tPowerCMS[B]", mt_prefix + "GroupCategoriesFolders${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</" + mt_prefix + "GroupCategoriesFolders>"),
            (mt_prefix + "GroupCategoriesFoldersFooter\tPowerCMS[B]", mt_prefix + "GroupCategoriesFoldersFooter>${1}</" + mt_prefix + "GroupCategoriesFoldersFooter>"),
            (mt_prefix + "GroupCategoriesFoldersHeader\tPowerCMS[B]", mt_prefix + "GroupCategoriesFoldersHeader>${1}</" + mt_prefix + "GroupCategoriesFoldersHeader>"),
            (mt_prefix + "GroupCategoriesFooter\tPowerCMS[B]", mt_prefix + "GroupCategoriesFooter>${1}</" + mt_prefix + "GroupCategoriesFooter>"),
            (mt_prefix + "GroupCategoriesHeader\tPowerCMS[B]", mt_prefix + "GroupCategoriesHeader>${1}</" + mt_prefix + "GroupCategoriesHeader>"),
            (mt_prefix + "GroupEntries\tPowerCMS[B]", mt_prefix + "GroupEntries${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</" + mt_prefix + "GroupEntries>"),
            (mt_prefix + "GroupEntriesFooter\tPowerCMS[B]", mt_prefix + "GroupEntriesFooter>${1}</" + mt_prefix + "GroupEntriesFooter>"),
            (mt_prefix + "GroupEntriesHeader\tPowerCMS[B]", mt_prefix + "GroupEntriesHeader>${1}</" + mt_prefix + "GroupEntriesHeader>"),
            (mt_prefix + "GroupEntriesPages\tPowerCMS[B]", mt_prefix + "GroupEntriesPages${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</" + mt_prefix + "GroupEntriesPages>"),
            (mt_prefix + "GroupEntriesPagesFooter\tPowerCMS[B]", mt_prefix + "GroupEntriesPagesFooter>${1}</" + mt_prefix + "GroupEntriesPagesFooter>"),
            (mt_prefix + "GroupEntriesPagesHeader\tPowerCMS[B]", mt_prefix + "GroupEntriesPagesHeader>${1}</" + mt_prefix + "GroupEntriesPagesHeader>"),
            (mt_prefix + "GroupFolders\tPowerCMS[B]", mt_prefix + "GroupFolders${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</" + mt_prefix + "GroupFolders>"),
            (mt_prefix + "GroupFoldersFooter\tPowerCMS[B]", mt_prefix + "GroupFoldersFooter>${1}</" + mt_prefix + "GroupFoldersFooter>"),
            (mt_prefix + "GroupFoldersHeader\tPowerCMS[B]", mt_prefix + "GroupFoldersHeader>${1}</" + mt_prefix + "GroupFoldersHeader>"),
            (mt_prefix + "GroupPages\tPowerCMS[B]", mt_prefix + "GroupPages${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</" + mt_prefix + "GroupPages>"),
            (mt_prefix + "GroupPagesFooter\tPowerCMS[B]", mt_prefix + "GroupPagesFooter>${1}</" + mt_prefix + "GroupPagesFooter>"),
            (mt_prefix + "GroupPagesHeader\tPowerCMS[B]", mt_prefix + "GroupPagesHeader>${1}</" + mt_prefix + "GroupPagesHeader>"),
            (mt_prefix + "GroupWebsites\tPowerCMS[B]", mt_prefix + "GroupWebsites${1: group=\"\"}${2: group_id=\"\"}${3: blog_id=\"\"}>${4}</" + mt_prefix + "GroupWebsites>"),
            (mt_prefix + "GroupWebsitesFooter\tPowerCMS[B]", mt_prefix + "GroupWebsitesFooter>${1}</" + mt_prefix + "GroupWebsitesFooter>"),
            (mt_prefix + "GroupWebsitesHeader\tPowerCMS[B]", mt_prefix + "GroupWebsitesHeader>${1}</" + mt_prefix + "GroupWebsitesHeader>"),
            (mt_prefix + "IfEntryChildrenFooter\tPowerCMS[B]", mt_prefix + "IfEntryChildrenFooter>${1}</" + mt_prefix + "IfEntryChildrenFooter>"),
            (mt_prefix + "IfEntryChildrenHeader\tPowerCMS[B]", mt_prefix + "IfEntryChildrenHeader>${1}</" + mt_prefix + "IfEntryChildrenHeader>"),
            (mt_prefix + "ImgAltCheck\tPowerCMS[B]", mt_prefix + "ImgAltCheck${1}>${2}</" + mt_prefix + "ImgAltCheck>"),
            (mt_prefix + "ImgAltCheckFooter\tPowerCMS[B]", mt_prefix + "ImgAltCheckFooter>${1}</" + mt_prefix + "ImgAltCheckFooter>"),
            (mt_prefix + "ImgAltCheckHeader\tPowerCMS[B]", mt_prefix + "ImgAltCheckHeader>${1}</" + mt_prefix + "ImgAltCheckHeader>"),
            (mt_prefix + "ItemGroupAssets\tPowerCMS[B]", mt_prefix + "ItemGroupAssets${1}>${2}</" + mt_prefix + "ItemGroupAssets>"),
            (mt_prefix + "ItemGroupAssetsFooter\tPowerCMS[B]", mt_prefix + "ItemGroupAssetsFooter>${1}</" + mt_prefix + "ItemGroupAssetsFooter>"),
            (mt_prefix + "ItemGroupAssetsHeader\tPowerCMS[B]", mt_prefix + "ItemGroupAssetsHeader>${1}</" + mt_prefix + "ItemGroupAssetsHeader>"),
            (mt_prefix + "ItemGroupBlogNext\tPowerCMS[B]", mt_prefix + "ItemGroupBlogNext${1}>${2}</" + mt_prefix + "ItemGroupBlogNext>"),
            (mt_prefix + "ItemGroupBlogPrevious\tPowerCMS[B]", mt_prefix + "ItemGroupBlogPrevious${1}>${2}</" + mt_prefix + "ItemGroupBlogPrevious>"),
            (mt_prefix + "ItemGroupBlogs\tPowerCMS[B]", mt_prefix + "ItemGroupBlogs${1}>${2}</" + mt_prefix + "ItemGroupBlogs>"),
            (mt_prefix + "ItemGroupBlogsFooter\tPowerCMS[B]", mt_prefix + "ItemGroupBlogsFooter>${1}</" + mt_prefix + "ItemGroupBlogsFooter>"),
            (mt_prefix + "ItemGroupBlogsHeader\tPowerCMS[B]", mt_prefix + "ItemGroupBlogsHeader>${1}</" + mt_prefix + "ItemGroupBlogsHeader>"),
            (mt_prefix + "ItemGroupCategories\tPowerCMS[B]", mt_prefix + "ItemGroupCategories${1}>${2}</" + mt_prefix + "ItemGroupCategories>"),
            (mt_prefix + "ItemGroupCategoriesFooter\tPowerCMS[B]", mt_prefix + "ItemGroupCategoriesFooter>${1}</" + mt_prefix + "ItemGroupCategoriesFooter>"),
            (mt_prefix + "ItemGroupCategoriesHeader\tPowerCMS[B]", mt_prefix + "ItemGroupCategoriesHeader>${1}</" + mt_prefix + "ItemGroupCategoriesHeader>"),
            (mt_prefix + "ItemGroupCategoryNext\tPowerCMS[B]", mt_prefix + "ItemGroupCategoryNext${1}>${2}</" + mt_prefix + "ItemGroupCategoryNext>"),
            (mt_prefix + "ItemGroupCategoryPrevious\tPowerCMS[B]", mt_prefix + "ItemGroupCategoryPrevious${1}>${2}</" + mt_prefix + "ItemGroupCategoryPrevious>"),
            (mt_prefix + "ItemGroupEntries\tPowerCMS[B]", mt_prefix + "ItemGroupEntries${1}>${2}</" + mt_prefix + "ItemGroupEntries>"),
            (mt_prefix + "ItemGroupEntriesFooter\tPowerCMS[B]", mt_prefix + "ItemGroupEntriesFooter>${1}</" + mt_prefix + "ItemGroupEntriesFooter>"),
            (mt_prefix + "ItemGroupEntriesHeader\tPowerCMS[B]", mt_prefix + "ItemGroupEntriesHeader>${1}</" + mt_prefix + "ItemGroupEntriesHeader>"),
            (mt_prefix + "ItemGroupEntryNext\tPowerCMS[B]", mt_prefix + "ItemGroupEntryNext${1}>${2}</" + mt_prefix + "ItemGroupEntryNext>"),
            (mt_prefix + "ItemGroupEntryPrevious\tPowerCMS[B]", mt_prefix + "ItemGroupEntryPrevious${1}>${2}</" + mt_prefix + "ItemGroupEntryPrevious>"),
            (mt_prefix + "JSCompressor\tPowerCMS[B]", mt_prefix + "JSCompressor${1}>${2}</" + mt_prefix + "JSCompressor>"),
            (mt_prefix + "KeitaiContent\tPowerCMS[B]", mt_prefix + "KeitaiContent${1}>${2}</" + mt_prefix + "KeitaiContent>"),
            (mt_prefix + "KeitaiContentBody\tPowerCMS[B]", mt_prefix + "KeitaiContentBody${1}>${2}</" + mt_prefix + "KeitaiContentBody>"),
            (mt_prefix + "KeitaiContentPageList\tPowerCMS[B]", mt_prefix + "KeitaiContentPageList${1}>${2}</" + mt_prefix + "KeitaiContentPageList>"),
            (mt_prefix + "KeitaiContentPageListFooter\tPowerCMS[B]", mt_prefix + "KeitaiContentPageListFooter>${1}</" + mt_prefix + "KeitaiContentPageListFooter>"),
            (mt_prefix + "KeitaiContentPageListHeader\tPowerCMS[B]", mt_prefix + "KeitaiContentPageListHeader>${1}</" + mt_prefix + "KeitaiContentPageListHeader>"),
            (mt_prefix + "LinkAuthor\tPowerCMS[B]", mt_prefix + "LinkAuthor${1}>${2}</" + mt_prefix + "LinkAuthor>"),
            (mt_prefix + "LinkBlock\tPowerCMS[B]", mt_prefix + "LinkBlock${1}>${2}</" + mt_prefix + "LinkBlock>"),
            (mt_prefix + "Links\tPowerCMS[B]", mt_prefix + "Links${1}>${2}</" + mt_prefix + "Links>"),
            (mt_prefix + "LinksFooter\tPowerCMS[B]", mt_prefix + "LinksFooter>${1}</" + mt_prefix + "LinksFooter>"),
            (mt_prefix + "LinksHeader\tPowerCMS[B]", mt_prefix + "LinksHeader>${1}</" + mt_prefix + "LinksHeader>"),
            (mt_prefix + "LinkTags\tPowerCMS[B]", mt_prefix + "LinkTags${1}>${2}</" + mt_prefix + "LinkTags>"),
            (mt_prefix + "ObjectGroupItems\tPowerCMS[B]", mt_prefix + "ObjectGroupItems${1}>${2}</" + mt_prefix + "ObjectGroupItems>"),
            (mt_prefix + "OGBlogs\tPowerCMS[B]", mt_prefix + "OGBlogs${1}>${2}</" + mt_prefix + "OGBlogs>"),
            (mt_prefix + "OGCategories\tPowerCMS[B]", mt_prefix + "OGCategories${1}>${2}</" + mt_prefix + "OGCategories>"),
            (mt_prefix + "OGEntries\tPowerCMS[B]", mt_prefix + "OGEntries${1}>${2}</" + mt_prefix + "OGEntries>"),
            (mt_prefix + "PageParentEntry\tPowerCMS[B]", mt_prefix + "PageParentEntry${1}>${2}</" + mt_prefix + "PageParentEntry>"),
            (mt_prefix + "Pager\tPowerCMS[B]", mt_prefix + "Pager${1}>${2}</" + mt_prefix + "Pager>"),
            (mt_prefix + "PagerBlock\tPowerCMS[B]", mt_prefix + "PagerBlock${1}>${2}</" + mt_prefix + "PagerBlock>"),
            (mt_prefix + "RemoveReturn\tPowerCMS[B]", mt_prefix + "RemoveReturn${1}>${2}</" + mt_prefix + "RemoveReturn>"),
            (mt_prefix + "RequestCache\tPowerCMS[B]", mt_prefix + "RequestCache${1}>${2}</" + mt_prefix + "RequestCache>"),
            (mt_prefix + "RequestCacheBlock\tPowerCMS[B]", mt_prefix + "RequestCacheBlock${1}>${2}</" + mt_prefix + "RequestCacheBlock>"),
            (mt_prefix + "SearchEntryField\tPowerCMS[B]", mt_prefix + "SearchEntryField${1}>${2}</" + mt_prefix + "SearchEntryField>"),
            (mt_prefix + "SetContext\tPowerCMS[B]", mt_prefix + "SetContext${1}>${2}</" + mt_prefix + "SetContext>"),
            (mt_prefix + "SetErrorHandler\tPowerCMS[B]", mt_prefix + "SetErrorHandler${1}>${2}</" + mt_prefix + "SetErrorHandler>"),
            (mt_prefix + "SetFolderContext\tPowerCMS[B]", mt_prefix + "SetFolderContext${1}>${2}</" + mt_prefix + "SetFolderContext>"),
            (mt_prefix + "SetTagContext\tPowerCMS[B]", mt_prefix + "SetTagContext${1}>${2}</" + mt_prefix + "SetTagContext>"),
            (mt_prefix + "StripLineFeeds\tPowerCMS[B]", mt_prefix + "StripLineFeeds${1}>${2}</" + mt_prefix + "StripLineFeeds>"),
            (mt_prefix + "StripTags\tPowerCMS[B]", mt_prefix + "StripTags${1}>${2}</" + mt_prefix + "StripTags>"),
            (mt_prefix + "TabSplitData\tPowerCMS[B]", mt_prefix + "TabSplitData${1}>${2}</" + mt_prefix + "TabSplitData>"),
            (mt_prefix + "TabSplitDatas\tPowerCMS[B]", mt_prefix + "TabSplitDatas${1}>${2}</" + mt_prefix + "TabSplitDatas>"),
            (mt_prefix + "Templates\tPowerCMS[B]", mt_prefix + "Templates${1}>${2}</" + mt_prefix + "Templates>"),
            (mt_prefix + "TemplatesFooter\tPowerCMS[B]", mt_prefix + "TemplatesFooter>${1}</" + mt_prefix + "TemplatesFooter>"),
            (mt_prefix + "TemplatesHeader\tPowerCMS[B]", mt_prefix + "TemplatesHeader>${1}</" + mt_prefix + "TemplatesHeader>"),
            (mt_prefix + "UserBookmarks\tPowerCMS[B]", mt_prefix + "UserBookmarks${1}>${2}</" + mt_prefix + "UserBookmarks>"),
            (mt_prefix + "ViewerUserContext\tPowerCMS[B]", mt_prefix + "ViewerUserContext${1}>${2}</" + mt_prefix + "ViewerUserContext>"),
            (mt_prefix + "Years\tPowerCMS[B]", mt_prefix + "Years${1}>${2}</" + mt_prefix + "Years>"),
            # Conditional Tag
            (mt_prefix + "BannerIfTagged\tPowerCMS[C]", mt_prefix + "BannerIfTagged${1}>${2}</" + mt_prefix + "BannerIfTagged>"),
            (mt_prefix + "CampaignIfTagged\tPowerCMS[C]", mt_prefix + "CampaignIfTagged${1}>${2}</" + mt_prefix + "CampaignIfTagged>"),
            (mt_prefix + "CustomObjectIfTagged\tPowerCMS[C]", mt_prefix + "CustomObjectIfTagged${1}>${2}</" + mt_prefix + "CustomObjectIfTagged>"),
            (mt_prefix + "IfActiveImage\tPowerCMS[C]", mt_prefix + "IfActiveImage${1}>${2}</" + mt_prefix + "IfActiveImage>"),
            (mt_prefix + "IfActiveLink\tPowerCMS[C]", mt_prefix + "IfActiveLink${1}>${2}</" + mt_prefix + "IfActiveLink>"),
            (mt_prefix + "IfActiveRSS\tPowerCMS[C]", mt_prefix + "IfActiveRSS${1}>${2}</" + mt_prefix + "IfActiveRSS>"),
            (mt_prefix + "IfAltsearchAnd_or\tPowerCMS[C]", mt_prefix + "IfAltsearchAnd_or${1}>${2}</" + mt_prefix + "IfAltsearchAnd_or>"),
            (mt_prefix + "IfAltsearchCategories_and_or\tPowerCMS[C]", mt_prefix + "IfAltsearchCategories_and_or${1}>${2}</" + mt_prefix + "IfAltsearchCategories_and_or>"),
            (mt_prefix + "IfAltsearchCurrentCategories\tPowerCMS[C]", mt_prefix + "IfAltsearchCurrentCategories${1}>${2}</" + mt_prefix + "IfAltsearchCurrentCategories>"),
            (mt_prefix + "IfAltsearchCurrentCategory\tPowerCMS[C]", mt_prefix + "IfAltsearchCurrentCategory${1}>${2}</" + mt_prefix + "IfAltsearchCurrentCategory>"),
            (mt_prefix + "IfAltsearchDate\tPowerCMS[C]", mt_prefix + "IfAltsearchDate${1}>${2}</" + mt_prefix + "IfAltsearchDate>"),
            (mt_prefix + "IfAltsearchFrom\tPowerCMS[C]", mt_prefix + "IfAltsearchFrom${1}>${2}</" + mt_prefix + "IfAltsearchFrom>"),
            (mt_prefix + "IfAltsearchMatchQuery\tPowerCMS[C]", mt_prefix + "IfAltsearchMatchQuery${1}>${2}</" + mt_prefix + "IfAltsearchMatchQuery>"),
            (mt_prefix + "IfAltsearchMetadatasFooter\tPowerCMS[C]", mt_prefix + "IfAltsearchMetadatasFooter>${1}</" + mt_prefix + "IfAltsearchMetadatasFooter>"),
            (mt_prefix + "IfAltsearchMetadatasHeader\tPowerCMS[C]", mt_prefix + "IfAltsearchMetadatasHeader>${1}</" + mt_prefix + "IfAltsearchMetadatasHeader>"),
            (mt_prefix + "IfAltsearchModeIsCategories\tPowerCMS[C]", mt_prefix + "IfAltsearchModeIsCategories${1}>${2}</" + mt_prefix + "IfAltsearchModeIsCategories>"),
            (mt_prefix + "IfAltsearchModeIsCategory\tPowerCMS[C]", mt_prefix + "IfAltsearchModeIsCategory${1}>${2}</" + mt_prefix + "IfAltsearchModeIsCategory>"),
            (mt_prefix + "IfAltsearchModeIsSubCategory\tPowerCMS[C]", mt_prefix + "IfAltsearchModeIsSubCategory${1}>${2}</" + mt_prefix + "IfAltsearchModeIsSubCategory>"),
            (mt_prefix + "IfAltsearchModeIsTag\tPowerCMS[C]", mt_prefix + "IfAltsearchModeIsTag${1}>${2}</" + mt_prefix + "IfAltsearchModeIsTag>"),
            (mt_prefix + "IfAltsearchNoneMatch\tPowerCMS[C]", mt_prefix + "IfAltsearchNoneMatch${1}>${2}</" + mt_prefix + "IfAltsearchNoneMatch>"),
            (mt_prefix + "IfAltsearchParam\tPowerCMS[C]", mt_prefix + "IfAltsearchParam${1}>${2}</" + mt_prefix + "IfAltsearchParam>"),
            (mt_prefix + "IfAltSearchParamDate\tPowerCMS[C]", mt_prefix + "IfAltSearchParamDate${1}>${2}</" + mt_prefix + "IfAltSearchParamDate>"),
            (mt_prefix + "IfAltsearchQuery\tPowerCMS[C]", mt_prefix + "IfAltsearchQuery${1}>${2}</" + mt_prefix + "IfAltsearchQuery>"),
            (mt_prefix + "IfAltsearchResultCurrent\tPowerCMS[C]", mt_prefix + "IfAltsearchResultCurrent${1}>${2}</" + mt_prefix + "IfAltsearchResultCurrent>"),
            (mt_prefix + "IfAltsearchResultNext\tPowerCMS[C]", mt_prefix + "IfAltsearchResultNext${1}>${2}</" + mt_prefix + "IfAltsearchResultNext>"),
            (mt_prefix + "IfAltsearchResultPrev\tPowerCMS[C]", mt_prefix + "IfAltsearchResultPrev${1}>${2}</" + mt_prefix + "IfAltsearchResultPrev>"),
            (mt_prefix + "IfAltsearchSort_by\tPowerCMS[C]", mt_prefix + "IfAltsearchSort_by${1}>${2}</" + mt_prefix + "IfAltsearchSort_by>"),
            (mt_prefix + "IfAltsearchSort_order\tPowerCMS[C]", mt_prefix + "IfAltsearchSort_order${1}>${2}</" + mt_prefix + "IfAltsearchSort_order>"),
            (mt_prefix + "IfAltsearchTo\tPowerCMS[C]", mt_prefix + "IfAltsearchTo${1}>${2}</" + mt_prefix + "IfAltsearchTo>"),
            (mt_prefix + "IfAndroid\tPowerCMS[C]", mt_prefix + "IfAndroid${1}>${2}</" + mt_prefix + "IfAndroid>"),
            (mt_prefix + "IfAuthorCanDropBox\tPowerCMS[C]", mt_prefix + "IfAuthorCanDropBox${1}>${2}</" + mt_prefix + "IfAuthorCanDropBox>"),
            (mt_prefix + "IfAuthorPostLimitInBlog\tPowerCMS[C]", mt_prefix + "IfAuthorPostLimitInBlog${1}>${2}</" + mt_prefix + "IfAuthorPostLimitInBlog>"),
            (mt_prefix + "IfBannerActive\tPowerCMS[C]", mt_prefix + "IfBannerActive${1}>${2}</" + mt_prefix + "IfBannerActive>"),
            (mt_prefix + "IfBannerHasImage\tPowerCMS[C]", mt_prefix + "IfBannerHasImage${1}>${2}</" + mt_prefix + "IfBannerHasImage>"),
            (mt_prefix + "IfBannerHasMovie\tPowerCMS[C]", mt_prefix + "IfBannerHasMovie${1}>${2}</" + mt_prefix + "IfBannerHasMovie>"),
            (mt_prefix + "IfBlogAttachFile\tPowerCMS[C]", mt_prefix + "IfBlogAttachFile${1}>${2}</" + mt_prefix + "IfBlogAttachFile>"),
            (mt_prefix + "IfBlogDynamicCache\tPowerCMS[C]", mt_prefix + "IfBlogDynamicCache${1}>${2}</" + mt_prefix + "IfBlogDynamicCache>"),
            (mt_prefix + "IfBlogDynamicConditional\tPowerCMS[C]", mt_prefix + "IfBlogDynamicConditional${1}>${2}</" + mt_prefix + "IfBlogDynamicConditional>"),
            (mt_prefix + "IfBlogDynamicMTML\tPowerCMS[C]", mt_prefix + "IfBlogDynamicMTML${1}>${2}</" + mt_prefix + "IfBlogDynamicMTML>"),
            (mt_prefix + "IfBlogTree\tPowerCMS[C]", mt_prefix + "IfBlogTree${1}>${2}</" + mt_prefix + "IfBlogTree>"),
            (mt_prefix + "IfBlogTreeEntryPublished\tPowerCMS[C]", mt_prefix + "IfBlogTreeEntryPublished${1}>${2}</" + mt_prefix + "IfBlogTreeEntryPublished>"),
            (mt_prefix + "IfBrokenImage\tPowerCMS[C]", mt_prefix + "IfBrokenImage${1}>${2}</" + mt_prefix + "IfBrokenImage>"),
            (mt_prefix + "IfBrokenLink\tPowerCMS[C]", mt_prefix + "IfBrokenLink${1}>${2}</" + mt_prefix + "IfBrokenLink>"),
            (mt_prefix + "IfBrokenRSS\tPowerCMS[C]", mt_prefix + "IfBrokenRSS${1}>${2}</" + mt_prefix + "IfBrokenRSS>"),
            (mt_prefix + "IfCampaignActive\tPowerCMS[C]", mt_prefix + "IfCampaignActive${1}>${2}</" + mt_prefix + "IfCampaignActive>"),
            (mt_prefix + "IfCampaignHasImage\tPowerCMS[C]", mt_prefix + "IfCampaignHasImage${1}>${2}</" + mt_prefix + "IfCampaignHasImage>"),
            (mt_prefix + "IfCampaignHasMovie\tPowerCMS[C]", mt_prefix + "IfCampaignHasMovie${1}>${2}</" + mt_prefix + "IfCampaignHasMovie>"),
            (mt_prefix + "IfCanCreateInCategory\tPowerCMS[C]", mt_prefix + "IfCanCreateInCategory${1}>${2}</" + mt_prefix + "IfCanCreateInCategory>"),
            (mt_prefix + "IfCategoryAttachFile\tPowerCMS[C]", mt_prefix + "IfCategoryAttachFile${1}>${2}</" + mt_prefix + "IfCategoryAttachFile>"),
            (mt_prefix + "IfCategoryIsTopLevel\tPowerCMS[C]", mt_prefix + "IfCategoryIsTopLevel${1}>${2}</" + mt_prefix + "IfCategoryIsTopLevel>"),
            (mt_prefix + "IfChildBlog\tPowerCMS[C]", mt_prefix + "IfChildBlog${1}>${2}</" + mt_prefix + "IfChildBlog>"),
            (mt_prefix + "IfCMS\tPowerCMS[C]", mt_prefix + "IfCMS${1}>${2}</" + mt_prefix + "IfCMS>"),
            (mt_prefix + "IfCMSIsBlog\tPowerCMS[C]", mt_prefix + "IfCMSIsBlog${1}>${2}</" + mt_prefix + "IfCMSIsBlog>"),
            (mt_prefix + "IfCMSParam\tPowerCMS[C]", mt_prefix + "IfCMSParam${1}>${2}</" + mt_prefix + "IfCMSParam>"),
            (mt_prefix + "IfCMSWebSite\tPowerCMS[C]", mt_prefix + "IfCMSWebSite${1}>${2}</" + mt_prefix + "IfCMSWebSite>"),
            (mt_prefix + "IfComponent\tPowerCMS[C]", mt_prefix + "IfComponent${1}>${2}</" + mt_prefix + "IfComponent>"),
            (mt_prefix + "IfContactFormIsClosed\tPowerCMS[C]", mt_prefix + "IfContactFormIsClosed${1}>${2}</" + mt_prefix + "IfContactFormIsClosed>"),
            (mt_prefix + "IfContactFormIsOpen\tPowerCMS[C]", mt_prefix + "IfContactFormIsOpen${1}>${2}</" + mt_prefix + "IfContactFormIsOpen>"),
            (mt_prefix + "IfContactFormIsPreOpen\tPowerCMS[C]", mt_prefix + "IfContactFormIsPreOpen${1}>${2}</" + mt_prefix + "IfContactFormIsPreOpen>"),
            (mt_prefix + "IfCurrentYear\tPowerCMS[C]", mt_prefix + "IfCurrentYear${1}>${2}</" + mt_prefix + "IfCurrentYear>"),
            (mt_prefix + "IfEnableEdit\tPowerCMS[C]", mt_prefix + "IfEnableEdit${1}>${2}</" + mt_prefix + "IfEnableEdit>"),
            (mt_prefix + "IfEntryAttachFile\tPowerCMS[C]", mt_prefix + "IfEntryAttachFile${1}>${2}</" + mt_prefix + "IfEntryAttachFile>"),
            (mt_prefix + "IfEntryCanEditable\tPowerCMS[C]", mt_prefix + "IfEntryCanEditable${1}>${2}</" + mt_prefix + "IfEntryCanEditable>"),
            (mt_prefix + "IfEntryIsDynamic\tPowerCMS[C]", mt_prefix + "IfEntryIsDynamic${1}>${2}</" + mt_prefix + "IfEntryIsDynamic>"),
            (mt_prefix + "IfEntryIsinCategory\tPowerCMS[C]", mt_prefix + "IfEntryIsinCategory${1}>${2}</" + mt_prefix + "IfEntryIsinCategory>"),
            (mt_prefix + "IfEntryPublished\tPowerCMS[C]", mt_prefix + "IfEntryPublished${1}>${2}</" + mt_prefix + "IfEntryPublished>"),
            (mt_prefix + "IfEntryUnpublished\tPowerCMS[C]", mt_prefix + "IfEntryUnpublished${1}>${2}</" + mt_prefix + "IfEntryUnpublished>"),
            (mt_prefix + "IfEstResultMatch\tPowerCMS[C]", mt_prefix + "IfEstResultMatch${1}>${2}</" + mt_prefix + "IfEstResultMatch>"),
            (mt_prefix + "IfEstResultNext\tPowerCMS[C]", mt_prefix + "IfEstResultNext${1}>${2}</" + mt_prefix + "IfEstResultNext>"),
            (mt_prefix + "IfEstResultPrev\tPowerCMS[C]", mt_prefix + "IfEstResultPrev${1}>${2}</" + mt_prefix + "IfEstResultPrev>"),
            (mt_prefix + "IfExtField\tPowerCMS[C]", mt_prefix + "IfExtField${1}>${2}</" + mt_prefix + "IfExtField>"),
            (mt_prefix + "IfExtFieldCompare\tPowerCMS[C]", mt_prefix + "IfExtFieldCompare${1}>${2}</" + mt_prefix + "IfExtFieldCompare>"),
            (mt_prefix + "IfExtFieldFileExists\tPowerCMS[C]", mt_prefix + "IfExtFieldFileExists${1}>${2}</" + mt_prefix + "IfExtFieldFileExists>"),
            (mt_prefix + "IfExtFieldNonEmpty\tPowerCMS[C]", mt_prefix + "IfExtFieldNonEmpty${1}>${2}</" + mt_prefix + "IfExtFieldNonEmpty>"),
            (mt_prefix + "IfExtFieldSelected\tPowerCMS[C]", mt_prefix + "IfExtFieldSelected${1}>${2}</" + mt_prefix + "IfExtFieldSelected>"),
            (mt_prefix + "IfExtFieldThumbnailExists\tPowerCMS[C]", mt_prefix + "IfExtFieldThumbnailExists${1}>${2}</" + mt_prefix + "IfExtFieldThumbnailExists>"),
            (mt_prefix + "IfExtFieldType\tPowerCMS[C]", mt_prefix + "IfExtFieldType${1}>${2}</" + mt_prefix + "IfExtFieldType>"),
            (mt_prefix + "IfExtFieldTypeImage\tPowerCMS[C]", mt_prefix + "IfExtFieldTypeImage${1}>${2}</" + mt_prefix + "IfExtFieldTypeImage>"),
            (mt_prefix + "IfFeedbackAlreadyPosted\tPowerCMS[C]", mt_prefix + "IfFeedbackAlreadyPosted${1}>${2}</" + mt_prefix + "IfFeedbackAlreadyPosted>"),
            (mt_prefix + "IfFormElementColumn\tPowerCMS[C]", mt_prefix + "IfFormElementColumn${1}>${2}</" + mt_prefix + "IfFormElementColumn>"),
            (mt_prefix + "IfFormElementRequired\tPowerCMS[C]", mt_prefix + "IfFormElementRequired${1}>${2}</" + mt_prefix + "IfFormElementRequired>"),
            (mt_prefix + "IfFormElementValidate\tPowerCMS[C]", mt_prefix + "IfFormElementValidate${1}>${2}</" + mt_prefix + "IfFormElementValidate>"),
            (mt_prefix + "IfHyperion\tPowerCMS[C]", mt_prefix + "IfHyperion${1}>${2}</" + mt_prefix + "IfHyperion>"),
            (mt_prefix + "IfIE\tPowerCMS[C]", mt_prefix + "IfIE${1}>${2}</" + mt_prefix + "IfIE>"),
            (mt_prefix + "IfiPad\tPowerCMS[C]", mt_prefix + "IfiPad${1}>${2}</" + mt_prefix + "IfiPad>"),
            (mt_prefix + "IfiPhone\tPowerCMS[C]", mt_prefix + "IfiPhone${1}>${2}</" + mt_prefix + "IfiPhone>"),
            (mt_prefix + "IfKeitai\tPowerCMS[C]", mt_prefix + "IfKeitai${1}>${2}</" + mt_prefix + "IfKeitai>"),
            (mt_prefix + "IfKeitaiPageCurrent\tPowerCMS[C]", mt_prefix + "IfKeitaiPageCurrent${1}>${2}</" + mt_prefix + "IfKeitaiPageCurrent>"),
            (mt_prefix + "IfKeitaiPageNext\tPowerCMS[C]", mt_prefix + "IfKeitaiPageNext${1}>${2}</" + mt_prefix + "IfKeitaiPageNext>"),
            (mt_prefix + "IfKeitaiPagePrev\tPowerCMS[C]", mt_prefix + "IfKeitaiPagePrev${1}>${2}</" + mt_prefix + "IfKeitaiPagePrev>"),
            (mt_prefix + "IfMemberLogin\tPowerCMS[C]", mt_prefix + "IfMemberLogin${1}>${2}</" + mt_prefix + "IfMemberLogin>"),
            (mt_prefix + "IfModule\tPowerCMS[C]", mt_prefix + "IfModule${1}>${2}</" + mt_prefix + "IfModule>"),
            (mt_prefix + "IfNonSystemScope\tPowerCMS[C]", mt_prefix + "IfNonSystemScope${1}>${2}</" + mt_prefix + "IfNonSystemScope>"),
            (mt_prefix + "IfNotSent\tPowerCMS[C]", mt_prefix + "IfNotSent${1}>${2}</" + mt_prefix + "IfNotSent>"),
            (mt_prefix + "IfObjectGroupItemIsBlog\tPowerCMS[C]", mt_prefix + "IfObjectGroupItemIsBlog${1}>${2}</" + mt_prefix + "IfObjectGroupItemIsBlog>"),
            (mt_prefix + "IfObjectGroupItemIsCategory\tPowerCMS[C]", mt_prefix + "IfObjectGroupItemIsCategory${1}>${2}</" + mt_prefix + "IfObjectGroupItemIsCategory>"),
            (mt_prefix + "IfObjectGroupItemIsEntry\tPowerCMS[C]", mt_prefix + "IfObjectGroupItemIsEntry${1}>${2}</" + mt_prefix + "IfObjectGroupItemIsEntry>"),
            (mt_prefix + "IfPagerCurrent\tPowerCMS[C]", mt_prefix + "IfPagerCurrent${1}>${2}</" + mt_prefix + "IfPagerCurrent>"),
            (mt_prefix + "IfPagerFooter\tPowerCMS[C]", mt_prefix + "IfPagerFooter>${1}</" + mt_prefix + "IfPagerFooter>"),
            (mt_prefix + "IfPagerHeader\tPowerCMS[C]", mt_prefix + "IfPagerHeader>${1}</" + mt_prefix + "IfPagerHeader>"),
            (mt_prefix + "IfPagerNext\tPowerCMS[C]", mt_prefix + "IfPagerNext${1}>${2}</" + mt_prefix + "IfPagerNext>"),
            (mt_prefix + "IfPagerPrev\tPowerCMS[C]", mt_prefix + "IfPagerPrev${1}>${2}</" + mt_prefix + "IfPagerPrev>"),
            (mt_prefix + "IfPC\tPowerCMS[C]", mt_prefix + "IfPC${1}>${2}</" + mt_prefix + "IfPC>"),
            (mt_prefix + "IfPerlModule\tPowerCMS[C]", mt_prefix + "IfPerlModule${1}>${2}</" + mt_prefix + "IfPerlModule>"),
            (mt_prefix + "IfPlugin\tPowerCMS[C]", mt_prefix + "IfPlugin${1}>${2}</" + mt_prefix + "IfPlugin>"),
            (mt_prefix + "IfPowerCMSFiles\tPowerCMS[C]", mt_prefix + "IfPowerCMSFiles${1}>${2}</" + mt_prefix + "IfPowerCMSFiles>"),
            (mt_prefix + "IfSecure\tPowerCMS[C]", mt_prefix + "IfSecure${1}>${2}</" + mt_prefix + "IfSecure>"),
            (mt_prefix + "IfSmartphone\tPowerCMS[C]", mt_prefix + "IfSmartphone${1}>${2}</" + mt_prefix + "IfSmartphone>"),
            (mt_prefix + "IfTablet\tPowerCMS[C]", mt_prefix + "IfTablet${1}>${2}</" + mt_prefix + "IfTablet>"),
            (mt_prefix + "IfTemplateSelector\tPowerCMS[C]", mt_prefix + "IfTemplateSelector${1}>${2}</" + mt_prefix + "IfTemplateSelector>"),
            (mt_prefix + "IfTemplateSelectorBlock\tPowerCMS[C]", mt_prefix + "IfTemplateSelectorBlock${1}>${2}</" + mt_prefix + "IfTemplateSelectorBlock>"),
            (mt_prefix + "IfTheURLFound\tPowerCMS[C]", mt_prefix + "IfTheURLFound${1}>${2}</" + mt_prefix + "IfTheURLFound>"),
            (mt_prefix + "IfURLFound\tPowerCMS[C]", mt_prefix + "IfURLFound${1}>${2}</" + mt_prefix + "IfURLFound>"),
            (mt_prefix + "IfUserCan\tPowerCMS[C]", mt_prefix + "IfUserCan${1}>${2}</" + mt_prefix + "IfUserCan>"),
            (mt_prefix + "IfUserCanCreateEntry\tPowerCMS[C]", mt_prefix + "IfUserCanCreateEntry${1}>${2}</" + mt_prefix + "IfUserCanCreateEntry>"),
            (mt_prefix + "IfUserCanCreatePage\tPowerCMS[C]", mt_prefix + "IfUserCanCreatePage${1}>${2}</" + mt_prefix + "IfUserCanCreatePage>"),
            (mt_prefix + "IfUserHasPerm\tPowerCMS[C]", mt_prefix + "IfUserHasPerm${1}>${2}</" + mt_prefix + "IfUserHasPerm>"),
            (mt_prefix + "IfUserIsSuperuser\tPowerCMS[C]", mt_prefix + "IfUserIsSuperuser${1}>${2}</" + mt_prefix + "IfUserIsSuperuser>"),
            (mt_prefix + "IfUserRole\tPowerCMS[C]", mt_prefix + "IfUserRole${1}>${2}</" + mt_prefix + "IfUserRole>"),
            (mt_prefix + "LinkIfTagged\tPowerCMS[C]", mt_prefix + "LinkIfTagged${1}>${2}</" + mt_prefix + "LinkIfTagged>"),
            (mt_prefix + "TemplateSelector\tPowerCMS[C]", mt_prefix + "TemplateSelector${1}>${2}</" + mt_prefix + "TemplateSelector>"),
            # Function Tag
            (mt_prefix + "AdminFullURL\tPowerCMS[F]", tag_open + mt_prefix + "AdminFullURL${1}" + tag_close),
            (mt_prefix + "AltSearchAnd_or\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchAnd_or${1}" + tag_close),
            (mt_prefix + "AltSearchBench\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchBench${1}" + tag_close),
            (mt_prefix + "AltSearchBlogID\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchBlogID${1}" + tag_close),
            (mt_prefix + "AltSearchCategories_and_or\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchCategories_and_or${1}" + tag_close),
            (mt_prefix + "AltSearchCategoryID\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchCategoryID${1}" + tag_close),
            (mt_prefix + "AltSearchCategoryIDs\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchCategoryIDs${1}" + tag_close),
            (mt_prefix + "AltSearchCategoryLabel\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchCategoryLabel${1}" + tag_close),
            (mt_prefix + "AltSearchCurrent\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchCurrent${1}" + tag_close),
            (mt_prefix + "AltSearchDate\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchDate${1}" + tag_close),
            (mt_prefix + "AltSearchDateParams\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchDateParams${1}" + tag_close),
            (mt_prefix + "AltSearchFeedPath\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchFeedPath${1}" + tag_close),
            (mt_prefix + "AltSearchFrom\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchFrom${1}" + tag_close),
            (mt_prefix + "AltSearchLast\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchLast${1}" + tag_close),
            (mt_prefix + "AltSearchLimit\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchLimit${1}" + tag_close),
            (mt_prefix + "AltSearchMatch\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchMatch${1}" + tag_close),
            (mt_prefix + "AltSearchNext\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchNext${1}" + tag_close),
            (mt_prefix + "AltSearchOffset\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchOffset${1}" + tag_close),
            (mt_prefix + "AltSearchPageCounter\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchPageCounter${1}" + tag_close),
            (mt_prefix + "AltSearchPages\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchPages${1}" + tag_close),
            (mt_prefix + "AltSearchParam\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchParam${1}" + tag_close),
            (mt_prefix + "AltSearchpath\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchpath${1}" + tag_close),
            (mt_prefix + "AltSearchPrev\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchPrev${1}" + tag_close),
            (mt_prefix + "AltSearchQuery\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchQuery${1}" + tag_close),
            (mt_prefix + "AltSearchResultNumber\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchResultNumber${1}" + tag_close),
            (mt_prefix + "AltSearchResultOffset\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchResultOffset${1}" + tag_close),
            (mt_prefix + "AltSearchResultPermalink\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchResultPermalink${1}" + tag_close),
            (mt_prefix + "AltSearchSort_by\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchSort_by${1}" + tag_close),
            (mt_prefix + "AltSearchSort_order\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchSort_order${1}" + tag_close),
            (mt_prefix + "AltSearchTo\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchTo${1}" + tag_close),
            (mt_prefix + "AltSearchURL\tPowerCMS[F]", tag_open + mt_prefix + "AltSearchURL${1}" + tag_close),
            (mt_prefix + "AssetGroupFieldScope\tPowerCMS[F]", tag_open + mt_prefix + "AssetGroupFieldScope${1}" + tag_close),
            (mt_prefix + "AttachFileCounter\tPowerCMS[F]", tag_open + mt_prefix + "AttachFileCounter${1}" + tag_close),
            (mt_prefix + "AuthorMobileEmail\tPowerCMS[F]", tag_open + mt_prefix + "AuthorMobileEmail${1}" + tag_close),
            (mt_prefix + "AuthorMobileToken\tPowerCMS[F]", tag_open + mt_prefix + "AuthorMobileToken${1}" + tag_close),
            (mt_prefix + "BannerAuthorDisplayName\tPowerCMS[F]", tag_open + mt_prefix + "BannerAuthorDisplayName${1}" + tag_close),
            (mt_prefix + "BannerBannerHeight\tPowerCMS[F]", tag_open + mt_prefix + "BannerBannerHeight${1}" + tag_close),
            (mt_prefix + "BannerBannerURL\tPowerCMS[F]", tag_open + mt_prefix + "BannerBannerURL${1}" + tag_close),
            (mt_prefix + "BannerBannerWidth\tPowerCMS[F]", tag_open + mt_prefix + "BannerBannerWidth${1}" + tag_close),
            (mt_prefix + "BannerBasename\tPowerCMS[F]", tag_open + mt_prefix + "BannerBasename${1}" + tag_close),
            (mt_prefix + "BannerClicks\tPowerCMS[F]", tag_open + mt_prefix + "BannerClicks${1}" + tag_close),
            (mt_prefix + "BannerConversion\tPowerCMS[F]", tag_open + mt_prefix + "BannerConversion${1}" + tag_close),
            (mt_prefix + "BannerConversionCounter\tPowerCMS[F]", tag_open + mt_prefix + "BannerConversionCounter${1}" + tag_close),
            (mt_prefix + "BannerConversionView\tPowerCMS[F]", tag_open + mt_prefix + "BannerConversionView${1}" + tag_close),
            (mt_prefix + "BannerCounter\tPowerCMS[F]", tag_open + mt_prefix + "BannerCounter${1}" + tag_close),
            (mt_prefix + "BannerCreatedOn\tPowerCMS[F]", tag_open + mt_prefix + "BannerCreatedOn${1}" + tag_close),
            (mt_prefix + "BannerDisplays\tPowerCMS[F]", tag_open + mt_prefix + "BannerDisplays${1}" + tag_close),
            (mt_prefix + "BannerFieldScope\tPowerCMS[F]", tag_open + mt_prefix + "BannerFieldScope${1}" + tag_close),
            (mt_prefix + "BannerID\tPowerCMS[F]", tag_open + mt_prefix + "BannerID${1}" + tag_close),
            (mt_prefix + "BannerMaxClicks\tPowerCMS[F]", tag_open + mt_prefix + "BannerMaxClicks${1}" + tag_close),
            (mt_prefix + "BannerMaxDisplays\tPowerCMS[F]", tag_open + mt_prefix + "BannerMaxDisplays${1}" + tag_close),
            (mt_prefix + "BannerMaxUniqClicks\tPowerCMS[F]", tag_open + mt_prefix + "BannerMaxUniqClicks${1}" + tag_close),
            (mt_prefix + "BannerMaxUniqDisplays\tPowerCMS[F]", tag_open + mt_prefix + "BannerMaxUniqDisplays${1}" + tag_close),
            (mt_prefix + "BannerMemo\tPowerCMS[F]", tag_open + mt_prefix + "BannerMemo${1}" + tag_close),
            (mt_prefix + "BannerMovieURL\tPowerCMS[F]", tag_open + mt_prefix + "BannerMovieURL${1}" + tag_close),
            (mt_prefix + "BannerPeriodOn\tPowerCMS[F]", tag_open + mt_prefix + "BannerPeriodOn${1}" + tag_close),
            (mt_prefix + "BannerPublishingOn\tPowerCMS[F]", tag_open + mt_prefix + "BannerPublishingOn${1}" + tag_close),
            (mt_prefix + "BannerRedirect\tPowerCMS[F]", tag_open + mt_prefix + "BannerRedirect${1}" + tag_close),
            (mt_prefix + "BannerScript\tPowerCMS[F]", tag_open + mt_prefix + "BannerScript${1}" + tag_close),
            (mt_prefix + "BannerText\tPowerCMS[F]", tag_open + mt_prefix + "BannerText${1}" + tag_close),
            (mt_prefix + "BannerTitle\tPowerCMS[F]", tag_open + mt_prefix + "BannerTitle${1}" + tag_close),
            (mt_prefix + "BannerUniqClicks\tPowerCMS[F]", tag_open + mt_prefix + "BannerUniqClicks${1}" + tag_close),
            (mt_prefix + "BannerUniqDisplays\tPowerCMS[F]", tag_open + mt_prefix + "BannerUniqDisplays${1}" + tag_close),
            (mt_prefix + "BannerURL\tPowerCMS[F]", tag_open + mt_prefix + "BannerURL${1}" + tag_close),
            (mt_prefix + "BlogDynamicCache\tPowerCMS[F]", tag_open + mt_prefix + "BlogDynamicCache${1}" + tag_close),
            (mt_prefix + "BlogDynamicConditional\tPowerCMS[F]", tag_open + mt_prefix + "BlogDynamicConditional${1}" + tag_close),
            (mt_prefix + "BlogDynamicDirectoryIndex\tPowerCMS[F]", tag_open + mt_prefix + "BlogDynamicDirectoryIndex${1}" + tag_close),
            (mt_prefix + "BlogDynamicExcludeExtension\tPowerCMS[F]", tag_open + mt_prefix + "BlogDynamicExcludeExtension${1}" + tag_close),
            (mt_prefix + "BlogDynamicExtension\tPowerCMS[F]", tag_open + mt_prefix + "BlogDynamicExtension${1}" + tag_close),
            (mt_prefix + "BlogDynamicMTMLCache\tPowerCMS[F]", tag_open + mt_prefix + "BlogDynamicMTMLCache${1}" + tag_close),
            (mt_prefix + "BlogDynamicMTMLConditional\tPowerCMS[F]", tag_open + mt_prefix + "BlogDynamicMTMLConditional${1}" + tag_close),
            (mt_prefix + "BlogDynamicSearchCache\tPowerCMS[F]", tag_open + mt_prefix + "BlogDynamicSearchCache${1}" + tag_close),
            (mt_prefix + "BlogDynamicSearchCacheExpiration\tPowerCMS[F]", tag_open + mt_prefix + "BlogDynamicSearchCacheExpiration${1}" + tag_close),
            (mt_prefix + "BlogDynamicSearchConditional\tPowerCMS[F]", tag_open + mt_prefix + "BlogDynamicSearchConditional${1}" + tag_close),
            (mt_prefix + "BlogFilesDirective\tPowerCMS[F]", tag_open + mt_prefix + "BlogFilesDirective${1}" + tag_close),
            (mt_prefix + "BlogFilesMatch\tPowerCMS[F]", tag_open + mt_prefix + "BlogFilesMatch${1}" + tag_close),
            (mt_prefix + "BlogFilesMatchDirective\tPowerCMS[F]", tag_open + mt_prefix + "BlogFilesMatchDirective${1}" + tag_close),
            (mt_prefix + "BlogIsMembersOnly\tPowerCMS[F]", tag_open + mt_prefix + "BlogIsMembersOnly${1}" + tag_close),
            (mt_prefix + "BlogTreeBlogNameTrim\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeBlogNameTrim${1}" + tag_close),
            (mt_prefix + "BlogTreeCatMaxDepth\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeCatMaxDepth${1}" + tag_close),
            (mt_prefix + "BlogTreeCatMaxDisplay\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeCatMaxDisplay${1}" + tag_close),
            (mt_prefix + "BlogTreeCommentCount\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeCommentCount${1}" + tag_close),
            (mt_prefix + "BlogTreeDashboardCSS\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeDashboardCSS${1}" + tag_close),
            (mt_prefix + "BlogTreeEntiesLastn\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeEntiesLastn${1}" + tag_close),
            (mt_prefix + "BlogTreeEntriesCount\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeEntriesCount${1}" + tag_close),
            (mt_prefix + "BlogTreeEntryTitleTrim\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeEntryTitleTrim${1}" + tag_close),
            (mt_prefix + "BlogTreeFolderCount\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeFolderCount${1}" + tag_close),
            (mt_prefix + "BlogTreeFormDataCount\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeFormDataCount${1}" + tag_close),
            (mt_prefix + "BlogTreePingCount\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreePingCount${1}" + tag_close),
            (mt_prefix + "BlogTreeTagCount\tPowerCMS[F]", tag_open + mt_prefix + "BlogTreeTagCount${1}" + tag_close),
            (mt_prefix + "BreadcrumbsLabel\tPowerCMS[F]", tag_open + mt_prefix + "BreadcrumbsLabel${1}" + tag_close),
            (mt_prefix + "BreadcrumbsLink\tPowerCMS[F]", tag_open + mt_prefix + "BreadcrumbsLink${1}" + tag_close),
            (mt_prefix + "BreadcrumbsTitle\tPowerCMS[F]", tag_open + mt_prefix + "BreadcrumbsTitle${1}" + tag_close),
            (mt_prefix + "BreadcrumbsURL\tPowerCMS[F]", tag_open + mt_prefix + "BreadcrumbsURL${1}" + tag_close),
            (mt_prefix + "CampaignAuthorDisplayName\tPowerCMS[F]", tag_open + mt_prefix + "CampaignAuthorDisplayName${1}" + tag_close),
            (mt_prefix + "CampaignBannerHeight\tPowerCMS[F]", tag_open + mt_prefix + "CampaignBannerHeight${1}" + tag_close),
            (mt_prefix + "CampaignBannerURL\tPowerCMS[F]", tag_open + mt_prefix + "CampaignBannerURL${1}" + tag_close),
            (mt_prefix + "CampaignBannerWidth\tPowerCMS[F]", tag_open + mt_prefix + "CampaignBannerWidth${1}" + tag_close),
            (mt_prefix + "CampaignBasename\tPowerCMS[F]", tag_open + mt_prefix + "CampaignBasename${1}" + tag_close),
            (mt_prefix + "CampaignClicks\tPowerCMS[F]", tag_open + mt_prefix + "CampaignClicks${1}" + tag_close),
            (mt_prefix + "CampaignConversion\tPowerCMS[F]", tag_open + mt_prefix + "CampaignConversion${1}" + tag_close),
            (mt_prefix + "CampaignConversionCounter\tPowerCMS[F]", tag_open + mt_prefix + "CampaignConversionCounter${1}" + tag_close),
            (mt_prefix + "CampaignConversionView\tPowerCMS[F]", tag_open + mt_prefix + "CampaignConversionView${1}" + tag_close),
            (mt_prefix + "CampaignCounter\tPowerCMS[F]", tag_open + mt_prefix + "CampaignCounter${1}" + tag_close),
            (mt_prefix + "CampaignCreatedOn\tPowerCMS[F]", tag_open + mt_prefix + "CampaignCreatedOn${1}" + tag_close),
            (mt_prefix + "CampaignDisplays\tPowerCMS[F]", tag_open + mt_prefix + "CampaignDisplays${1}" + tag_close),
            (mt_prefix + "CampaignFieldScope\tPowerCMS[F]", tag_open + mt_prefix + "CampaignFieldScope${1}" + tag_close),
            (mt_prefix + "CampaignID\tPowerCMS[F]", tag_open + mt_prefix + "CampaignID${1}" + tag_close),
            (mt_prefix + "CampaignMaxClicks\tPowerCMS[F]", tag_open + mt_prefix + "CampaignMaxClicks${1}" + tag_close),
            (mt_prefix + "CampaignMaxDisplays\tPowerCMS[F]", tag_open + mt_prefix + "CampaignMaxDisplays${1}" + tag_close),
            (mt_prefix + "CampaignMaxUniqClicks\tPowerCMS[F]", tag_open + mt_prefix + "CampaignMaxUniqClicks${1}" + tag_close),
            (mt_prefix + "CampaignMaxUniqDisplays\tPowerCMS[F]", tag_open + mt_prefix + "CampaignMaxUniqDisplays${1}" + tag_close),
            (mt_prefix + "CampaignMemo\tPowerCMS[F]", tag_open + mt_prefix + "CampaignMemo${1}" + tag_close),
            (mt_prefix + "CampaignMovieURL\tPowerCMS[F]", tag_open + mt_prefix + "CampaignMovieURL${1}" + tag_close),
            (mt_prefix + "CampaignPeriodOn\tPowerCMS[F]", tag_open + mt_prefix + "CampaignPeriodOn${1}" + tag_close),
            (mt_prefix + "CampaignPublishingOn\tPowerCMS[F]", tag_open + mt_prefix + "CampaignPublishingOn${1}" + tag_close),
            (mt_prefix + "CampaignRedirect\tPowerCMS[F]", tag_open + mt_prefix + "CampaignRedirect${1}" + tag_close),
            (mt_prefix + "CampaignScript\tPowerCMS[F]", tag_open + mt_prefix + "CampaignScript${1}" + tag_close),
            (mt_prefix + "CampaignText\tPowerCMS[F]", tag_open + mt_prefix + "CampaignText${1}" + tag_close),
            (mt_prefix + "CampaignTitle\tPowerCMS[F]", tag_open + mt_prefix + "CampaignTitle${1}" + tag_close),
            (mt_prefix + "CampaignUniqClicks\tPowerCMS[F]", tag_open + mt_prefix + "CampaignUniqClicks${1}" + tag_close),
            (mt_prefix + "CampaignUniqDisplays\tPowerCMS[F]", tag_open + mt_prefix + "CampaignUniqDisplays${1}" + tag_close),
            (mt_prefix + "CampaignURL\tPowerCMS[F]", tag_open + mt_prefix + "CampaignURL${1}" + tag_close),
            (mt_prefix + "CategoryClass\tPowerCMS[F]", tag_open + mt_prefix + "CategoryClass${1}" + tag_close),
            (mt_prefix + "CGIMaxUpload\tPowerCMS[F]", tag_open + mt_prefix + "CGIMaxUpload${1}" + tag_close),
            (mt_prefix + "CMSParam\tPowerCMS[F]", tag_open + mt_prefix + "CMSParam${1}" + tag_close),
            (mt_prefix + "ComponentPath\tPowerCMS[F]", tag_open + mt_prefix + "ComponentPath${1}" + tag_close),
            (mt_prefix + "ContactFormAuthorDisplayName\tPowerCMS[F]", tag_open + mt_prefix + "ContactFormAuthorDisplayName${1}" + tag_close),
            (mt_prefix + "ContactFormColumn\tPowerCMS[F]", tag_open + mt_prefix + "ContactFormColumn${1}" + tag_close),
            (mt_prefix + "ContactFormFieldScope\tPowerCMS[F]", tag_open + mt_prefix + "ContactFormFieldScope${1}" + tag_close),
            (mt_prefix + "ContactFormID\tPowerCMS[F]", tag_open + mt_prefix + "ContactFormID${1}" + tag_close),
            (mt_prefix + "ContactFormName\tPowerCMS[F]", tag_open + mt_prefix + "ContactFormName${1}" + tag_close),
            (mt_prefix + "ContactFormScript\tPowerCMS[F]", tag_open + mt_prefix + "ContactFormScript${1}" + tag_close),
            (mt_prefix + "ContactFormStaticLink\tPowerCMS[F]", tag_open + mt_prefix + "ContactFormStaticLink${1}" + tag_close),
            (mt_prefix + "CookieDump\tPowerCMS[F]", tag_open + mt_prefix + "CookieDump${1}" + tag_close),
            (mt_prefix + "CountGroupCount\tPowerCMS[F]", tag_open + mt_prefix + "CountGroupCount${1}" + tag_close),
            (mt_prefix + "CountGroupValue\tPowerCMS[F]", tag_open + mt_prefix + "CountGroupValue${1}" + tag_close),
            (mt_prefix + "CurrentDate\tPowerCMS[F]", tag_open + mt_prefix + "CurrentDate${1}" + tag_close),
            (mt_prefix + "CustomConfigAuthorDisplayName\tPowerCMS[F]", tag_open + mt_prefix + "CustomConfigAuthorDisplayName${1}" + tag_close),
            (mt_prefix + "CustomConfigCreatedOn\tPowerCMS[F]", tag_open + mt_prefix + "CustomConfigCreatedOn${1}" + tag_close),
            (mt_prefix + "CustomConfigID\tPowerCMS[F]", tag_open + mt_prefix + "CustomConfigID${1}" + tag_close),
            (mt_prefix + "CustomConfigKey\tPowerCMS[F]", tag_open + mt_prefix + "CustomConfigKey${1}" + tag_close),
            (mt_prefix + "CustomConfigModifiedOn\tPowerCMS[F]", tag_open + mt_prefix + "CustomConfigModifiedOn${1}" + tag_close),
            (mt_prefix + "CustomConfigName\tPowerCMS[F]", tag_open + mt_prefix + "CustomConfigName${1}" + tag_close),
            (mt_prefix + "CustomConfigPriority\tPowerCMS[F]", tag_open + mt_prefix + "CustomConfigPriority${1}" + tag_close),
            (mt_prefix + "CustomConfigValue\tPowerCMS[F]", tag_open + mt_prefix + "CustomConfigValue${1}" + tag_close),
            (mt_prefix + "CustomFieldColumnValue\tPowerCMS[F]", tag_open + mt_prefix + "CustomFieldColumnValue${1}" + tag_close),
            (mt_prefix + "CustomFieldQuery\tPowerCMS[F]", tag_open + mt_prefix + "CustomFieldQuery${1}" + tag_close),
            (mt_prefix + "CustomFieldType\tPowerCMS[F]", tag_open + mt_prefix + "CustomFieldType${1}" + tag_close),
            (mt_prefix + "CustomGroupFieldScope\tPowerCMS[F]", tag_open + mt_prefix + "CustomGroupFieldScope${1}" + tag_close),
            (mt_prefix + "CustomGroupName\tPowerCMS[F]", tag_open + mt_prefix + "CustomGroupName${1}" + tag_close),
            (mt_prefix + "CustomGroupOrder\tPowerCMS[F]", tag_open + mt_prefix + "CustomGroupOrder${1}" + tag_close),
            (mt_prefix + "CustomObjectAuthorDisplayName\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectAuthorDisplayName${1}" + tag_close),
            (mt_prefix + "CustomObjectAuthoredOn\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectAuthoredOn${1}" + tag_close),
            (mt_prefix + "CustomObjectBasename\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectBasename${1}" + tag_close),
            (mt_prefix + "CustomObjectBlogID\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectBlogID${1}" + tag_close),
            (mt_prefix + "CustomObjectBody\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectBody${1}" + tag_close),
            (mt_prefix + "CustomObjectColumn\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectColumn${1}" + tag_close),
            (mt_prefix + "CustomObjectColumnName\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectColumnName${1}" + tag_close),
            (mt_prefix + "CustomObjectColumnValue\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectColumnValue${1}" + tag_close),
            (mt_prefix + "CustomObjectCreatedOn\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectCreatedOn${1}" + tag_close),
            (mt_prefix + "CustomObjectFieldScope\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectFieldScope${1}" + tag_close),
            (mt_prefix + "CustomObjectFolderLink\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectFolderLink${1}" + tag_close),
            (mt_prefix + "CustomObjectID\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectID${1}" + tag_close),
            (mt_prefix + "CustomObjectKeywords\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectKeywords${1}" + tag_close),
            (mt_prefix + "CustomObjectLabel\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectLabel${1}" + tag_close),
            (mt_prefix + "CustomObjectModifiedOn\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectModifiedOn${1}" + tag_close),
            (mt_prefix + "CustomObjectName\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectName${1}" + tag_close),
            (mt_prefix + "CustomObjectPeriodOn\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectPeriodOn${1}" + tag_close),
            (mt_prefix + "CustomObjectPermalink\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectPermalink${1}" + tag_close),
            (mt_prefix + "CustomObjectsCount\tPowerCMS[F]", tag_open + mt_prefix + "CustomObjectsCount${1}" + tag_close),
            (mt_prefix + "DownloadScript\tPowerCMS[F]", tag_open + mt_prefix + "DownloadScript${1}" + tag_close),
            (mt_prefix + "DynamicSiteBootstrapper\tPowerCMS[F]", tag_open + mt_prefix + "DynamicSiteBootstrapper${1}" + tag_close),
            (mt_prefix + "EntryAttachFile\tPowerCMS[F]", tag_open + mt_prefix + "EntryAttachFile${1}" + tag_close),
            (mt_prefix + "EntryAttachFilesValues\tPowerCMS[F]", tag_open + mt_prefix + "EntryAttachFilesValues${1}" + tag_close),
            (mt_prefix + "EntryChildrenCounter\tPowerCMS[F]", tag_open + mt_prefix + "EntryChildrenCounter${1}" + tag_close),
            (mt_prefix + "EntryCreatorDisplayName\tPowerCMS[F]", tag_open + mt_prefix + "EntryCreatorDisplayName${1}" + tag_close),
            (mt_prefix + "EntryCreatorID\tPowerCMS[F]", tag_open + mt_prefix + "EntryCreatorID${1}" + tag_close),
            (mt_prefix + "EntryExtDatas\tPowerCMS[F]", tag_open + mt_prefix + "EntryExtDatas${1}" + tag_close),
            (mt_prefix + "EntryFieldScope\tPowerCMS[F]", tag_open + mt_prefix + "EntryFieldScope${1}" + tag_close),
            (mt_prefix + "EntryParentID\tPowerCMS[F]", tag_open + mt_prefix + "EntryParentID${1}" + tag_close),
            (mt_prefix + "EntryPostCount\tPowerCMS[F]", tag_open + mt_prefix + "EntryPostCount${1}" + tag_close),
            (mt_prefix + "EntryPublishedOn\tPowerCMS[F]", tag_open + mt_prefix + "EntryPublishedOn${1}" + tag_close),
            (mt_prefix + "EntryStatus\tPowerCMS[F]", tag_open + mt_prefix + "EntryStatus${1}" + tag_close),
            (mt_prefix + "EntryStatusNumber\tPowerCMS[F]", tag_open + mt_prefix + "EntryStatusNumber${1}" + tag_close),
            (mt_prefix + "EntryTemplateName\tPowerCMS[F]", tag_open + mt_prefix + "EntryTemplateName${1}" + tag_close),
            (mt_prefix + "EntryUnpublishedOn\tPowerCMS[F]", tag_open + mt_prefix + "EntryUnpublishedOn${1}" + tag_close),
            (mt_prefix + "EnvDump\tPowerCMS[F]", tag_open + mt_prefix + "EnvDump${1}" + tag_close),
            (mt_prefix + "Error\tPowerCMS[F]", tag_open + mt_prefix + "Error${1}" + tag_close),
            (mt_prefix + "EstCmdPath\tPowerCMS[F]", tag_open + mt_prefix + "EstCmdPath${1}" + tag_close),
            (mt_prefix + "EstDbPath\tPowerCMS[F]", tag_open + mt_prefix + "EstDbPath${1}" + tag_close),
            (mt_prefix + "EstraierScript\tPowerCMS[F]", tag_open + mt_prefix + "EstraierScript${1}" + tag_close),
            (mt_prefix + "EstResultAttribute\tPowerCMS[F]", tag_open + mt_prefix + "EstResultAttribute${1}" + tag_close),
            (mt_prefix + "EstResultCount\tPowerCMS[F]", tag_open + mt_prefix + "EstResultCount${1}" + tag_close),
            (mt_prefix + "EstResultDate\tPowerCMS[F]", tag_open + mt_prefix + "EstResultDate${1}" + tag_close),
            (mt_prefix + "EstResultEntryBlogID\tPowerCMS[F]", tag_open + mt_prefix + "EstResultEntryBlogID${1}" + tag_close),
            (mt_prefix + "EstResultEntryID\tPowerCMS[F]", tag_open + mt_prefix + "EstResultEntryID${1}" + tag_close),
            (mt_prefix + "EstResultExcerpt\tPowerCMS[F]", tag_open + mt_prefix + "EstResultExcerpt${1}" + tag_close),
            (mt_prefix + "EstResultTitle\tPowerCMS[F]", tag_open + mt_prefix + "EstResultTitle${1}" + tag_close),
            (mt_prefix + "EstResultURL\tPowerCMS[F]", tag_open + mt_prefix + "EstResultURL${1}" + tag_close),
            (mt_prefix + "ExtFieldAlt\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldAlt${1}" + tag_close),
            (mt_prefix + "ExtFieldCBLabel\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldCBLabel${1}" + tag_close),
            (mt_prefix + "ExtFieldCount\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldCount${1}" + tag_close),
            (mt_prefix + "ExtFieldCounter\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldCounter${1}" + tag_close),
            (mt_prefix + "ExtFieldDescription\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldDescription${1}" + tag_close),
            (mt_prefix + "ExtFieldExportData\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldExportData${1}" + tag_close),
            (mt_prefix + "ExtFieldFileDate\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldFileDate${1}" + tag_close),
            (mt_prefix + "ExtFieldFileName\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldFileName${1}" + tag_close),
            (mt_prefix + "ExtFieldFilePath\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldFilePath${1}" + tag_close),
            (mt_prefix + "ExtFieldFileSize\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldFileSize${1}" + tag_close),
            (mt_prefix + "ExtFieldFileSuffix\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldFileSuffix${1}" + tag_close),
            (mt_prefix + "ExtFieldFileThumbnail\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldFileThumbnail${1}" + tag_close),
            (mt_prefix + "ExtFieldID\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldID${1}" + tag_close),
            (mt_prefix + "ExtFieldImageHeight\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldImageHeight${1}" + tag_close),
            (mt_prefix + "ExtFieldImageWidth\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldImageWidth${1}" + tag_close),
            (mt_prefix + "ExtFieldLabel\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldLabel${1}" + tag_close),
            (mt_prefix + "ExtFieldMultiValue\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldMultiValue${1}" + tag_close),
            (mt_prefix + "ExtFieldName\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldName${1}" + tag_close),
            (mt_prefix + "ExtFieldNum\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldNum${1}" + tag_close),
            (mt_prefix + "ExtFieldText\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldText${1}" + tag_close),
            (mt_prefix + "ExtFieldThumbnail\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldThumbnail${1}" + tag_close),
            (mt_prefix + "ExtFieldThumbnailHeight\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldThumbnailHeight${1}" + tag_close),
            (mt_prefix + "ExtFieldThumbnailWidth\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldThumbnailWidth${1}" + tag_close),
            (mt_prefix + "ExtFieldValue\tPowerCMS[F]", tag_open + mt_prefix + "ExtFieldValue${1}" + tag_close),
            (mt_prefix + "FeedbackClosedMessage\tPowerCMS[F]", tag_open + mt_prefix + "FeedbackClosedMessage${1}" + tag_close),
            (mt_prefix + "FeedbackConfirmMessage\tPowerCMS[F]", tag_open + mt_prefix + "FeedbackConfirmMessage${1}" + tag_close),
            (mt_prefix + "FeedbackCount\tPowerCMS[F]", tag_open + mt_prefix + "FeedbackCount${1}" + tag_close),
            (mt_prefix + "FeedbackErrorMessage\tPowerCMS[F]", tag_open + mt_prefix + "FeedbackErrorMessage${1}" + tag_close),
            (mt_prefix + "FeedbackInformationMessage\tPowerCMS[F]", tag_open + mt_prefix + "FeedbackInformationMessage${1}" + tag_close),
            (mt_prefix + "FeedbackPreOpenMessage\tPowerCMS[F]", tag_open + mt_prefix + "FeedbackPreOpenMessage${1}" + tag_close),
            (mt_prefix + "FeedbackThanksMessage\tPowerCMS[F]", tag_open + mt_prefix + "FeedbackThanksMessage${1}" + tag_close),
            (mt_prefix + "FileGetContents\tPowerCMS[F]", tag_open + mt_prefix + "FileGetContents${1}" + tag_close),
            (mt_prefix + "FormCMSFormStatusMsg\tPowerCMS[F]", tag_open + mt_prefix + "FormCMSFormStatusMsg${1}" + tag_close),
            (mt_prefix + "FormCMSHTML\tPowerCMS[F]", tag_open + mt_prefix + "FormCMSHTML${1}" + tag_close),
            (mt_prefix + "FormElementBasename\tPowerCMS[F]", tag_open + mt_prefix + "FormElementBasename${1}" + tag_close),
            (mt_prefix + "FormElementColumn\tPowerCMS[F]", tag_open + mt_prefix + "FormElementColumn${1}" + tag_close),
            (mt_prefix + "FormElementDefault\tPowerCMS[F]", tag_open + mt_prefix + "FormElementDefault${1}" + tag_close),
            (mt_prefix + "FormElementDescription\tPowerCMS[F]", tag_open + mt_prefix + "FormElementDescription${1}" + tag_close),
            (mt_prefix + "FormElementHTML\tPowerCMS[F]", tag_open + mt_prefix + "FormElementHTML${1}" + tag_close),
            (mt_prefix + "FormElementName\tPowerCMS[F]", tag_open + mt_prefix + "FormElementName${1}" + tag_close),
            (mt_prefix + "FormElementOption\tPowerCMS[F]", tag_open + mt_prefix + "FormElementOption${1}" + tag_close),
            (mt_prefix + "FormElementSize\tPowerCMS[F]", tag_open + mt_prefix + "FormElementSize${1}" + tag_close),
            (mt_prefix + "FormElementType\tPowerCMS[F]", tag_open + mt_prefix + "FormElementType${1}" + tag_close),
            (mt_prefix + "FormScript\tPowerCMS[F]", tag_open + mt_prefix + "FormScript${1}" + tag_close),
            (mt_prefix + "GAHotEntriesCount\tPowerCMS[F]", tag_open + mt_prefix + "GAHotEntriesCount${1}" + tag_close),
            (mt_prefix + "GALastUpdateTs\tPowerCMS[F]", tag_open + mt_prefix + "GALastUpdateTs${1}" + tag_close),
            (mt_prefix + "GATrackingCode\tPowerCMS[F]", tag_open + mt_prefix + "GATrackingCode${1}" + tag_close),
            (mt_prefix + "GetCareer\tPowerCMS[F]", tag_open + mt_prefix + "GetCareer${1}" + tag_close),
            (mt_prefix + "GetCookie\tPowerCMS[F]", tag_open + mt_prefix + "GetCookie${1}" + tag_close),
            (mt_prefix + "GetEmoji\tPowerCMS[F]", tag_open + mt_prefix + "GetEmoji${1}" + tag_close),
            (mt_prefix + "GetEmojiLegacy\tPowerCMS[F]", tag_open + mt_prefix + "GetEmojiLegacy${1}" + tag_close),
            (mt_prefix + "GetEmojiRegacy\tPowerCMS[F]", tag_open + mt_prefix + "GetEmojiRegacy${1}" + tag_close),
            (mt_prefix + "GetEmojiUnicode\tPowerCMS[F]", tag_open + mt_prefix + "GetEmojiUnicode${1}" + tag_close),
            (mt_prefix + "GetEmoticon\tPowerCMS[F]", tag_open + mt_prefix + "GetEmoticon${1}" + tag_close),
            (mt_prefix + "GetEnv\tPowerCMS[F]", tag_open + mt_prefix + "GetEnv${1}" + tag_close),
            (mt_prefix + "GetObjectChildLabel\tPowerCMS[F]", tag_open + mt_prefix + "GetObjectChildLabel${1}" + tag_close),
            (mt_prefix + "GetObjectClassLabel\tPowerCMS[F]", tag_open + mt_prefix + "GetObjectClassLabel${1}" + tag_close),
            (mt_prefix + "GetUnicodeEmoji\tPowerCMS[F]", tag_open + mt_prefix + "GetUnicodeEmoji${1}" + tag_close),
            (mt_prefix + "ImgAltCheckAlertCount\tPowerCMS[F]", tag_open + mt_prefix + "ImgAltCheckAlertCount${1}" + tag_close),
            (mt_prefix + "ImgAltCheckErrorCode\tPowerCMS[F]", tag_open + mt_prefix + "ImgAltCheckErrorCode${1}" + tag_close),
            (mt_prefix + "ImgAltCheckErrorCount\tPowerCMS[F]", tag_open + mt_prefix + "ImgAltCheckErrorCount${1}" + tag_close),
            (mt_prefix + "ImgAltCheckErrorMessage\tPowerCMS[F]", tag_open + mt_prefix + "ImgAltCheckErrorMessage${1}" + tag_close),
            (mt_prefix + "ImgAltCheckFilename\tPowerCMS[F]", tag_open + mt_prefix + "ImgAltCheckFilename${1}" + tag_close),
            (mt_prefix + "ImgAltCheckImgAlt\tPowerCMS[F]", tag_open + mt_prefix + "ImgAltCheckImgAlt${1}" + tag_close),
            (mt_prefix + "ImgAltCheckImgSrc\tPowerCMS[F]", tag_open + mt_prefix + "ImgAltCheckImgSrc${1}" + tag_close),
            (mt_prefix + "ISCreatePosts\tPowerCMS[F]", tag_open + mt_prefix + "ISCreatePosts${1}" + tag_close),
            (mt_prefix + "ItemGroupBlogsCount\tPowerCMS[F]", tag_open + mt_prefix + "ItemGroupBlogsCount${1}" + tag_close),
            (mt_prefix + "ItemGroupCategoriesCount\tPowerCMS[F]", tag_open + mt_prefix + "ItemGroupCategoriesCount${1}" + tag_close),
            (mt_prefix + "ItemGroupEntriesCount\tPowerCMS[F]", tag_open + mt_prefix + "ItemGroupEntriesCount${1}" + tag_close),
            (mt_prefix + "KeitaiEmoticonSize\tPowerCMS[F]", tag_open + mt_prefix + "KeitaiEmoticonSize${1}" + tag_close),
            (mt_prefix + "KeitaiPageCount\tPowerCMS[F]", tag_open + mt_prefix + "KeitaiPageCount${1}" + tag_close),
            (mt_prefix + "KeitaiPageLink\tPowerCMS[F]", tag_open + mt_prefix + "KeitaiPageLink${1}" + tag_close),
            (mt_prefix + "KeitaiPageNextLink\tPowerCMS[F]", tag_open + mt_prefix + "KeitaiPageNextLink${1}" + tag_close),
            (mt_prefix + "KeitaiPageNumber\tPowerCMS[F]", tag_open + mt_prefix + "KeitaiPageNumber${1}" + tag_close),
            (mt_prefix + "KeitaiPagePrevLink\tPowerCMS[F]", tag_open + mt_prefix + "KeitaiPagePrevLink${1}" + tag_close),
            (mt_prefix + "LatestRevisionValue\tPowerCMS[F]", tag_open + mt_prefix + "LatestRevisionValue${1}" + tag_close),
            (mt_prefix + "LinkAuthorDisplayName\tPowerCMS[F]", tag_open + mt_prefix + "LinkAuthorDisplayName${1}" + tag_close),
            (mt_prefix + "LinkAuthoredOn\tPowerCMS[F]", tag_open + mt_prefix + "LinkAuthoredOn${1}" + tag_close),
            (mt_prefix + "LinkBlogID\tPowerCMS[F]", tag_open + mt_prefix + "LinkBlogID${1}" + tag_close),
            (mt_prefix + "LinkCreatedOn\tPowerCMS[F]", tag_open + mt_prefix + "LinkCreatedOn${1}" + tag_close),
            (mt_prefix + "LinkDescription\tPowerCMS[F]", tag_open + mt_prefix + "LinkDescription${1}" + tag_close),
            (mt_prefix + "LinkFieldScope\tPowerCMS[F]", tag_open + mt_prefix + "LinkFieldScope${1}" + tag_close),
            (mt_prefix + "LinkHTML\tPowerCMS[F]", tag_open + mt_prefix + "LinkHTML${1}" + tag_close),
            (mt_prefix + "LinkImageAddress\tPowerCMS[F]", tag_open + mt_prefix + "LinkImageAddress${1}" + tag_close),
            (mt_prefix + "LinkModifiedOn\tPowerCMS[F]", tag_open + mt_prefix + "LinkModifiedOn${1}" + tag_close),
            (mt_prefix + "LinkName\tPowerCMS[F]", tag_open + mt_prefix + "LinkName${1}" + tag_close),
            (mt_prefix + "LinkNotes\tPowerCMS[F]", tag_open + mt_prefix + "LinkNotes${1}" + tag_close),
            (mt_prefix + "LinkRating\tPowerCMS[F]", tag_open + mt_prefix + "LinkRating${1}" + tag_close),
            (mt_prefix + "LinkRel\tPowerCMS[F]", tag_open + mt_prefix + "LinkRel${1}" + tag_close),
            (mt_prefix + "LinkRSSAddress\tPowerCMS[F]", tag_open + mt_prefix + "LinkRSSAddress${1}" + tag_close),
            (mt_prefix + "LinkRSSUpdatedOn\tPowerCMS[F]", tag_open + mt_prefix + "LinkRSSUpdatedOn${1}" + tag_close),
            (mt_prefix + "LinkTarget\tPowerCMS[F]", tag_open + mt_prefix + "LinkTarget${1}" + tag_close),
            (mt_prefix + "LinkTitle\tPowerCMS[F]", tag_open + mt_prefix + "LinkTitle${1}" + tag_close),
            (mt_prefix + "LinkURL\tPowerCMS[F]", tag_open + mt_prefix + "LinkURL${1}" + tag_close),
            (mt_prefix + "LinkURLUpdatedOn\tPowerCMS[F]", tag_open + mt_prefix + "LinkURLUpdatedOn${1}" + tag_close),
            (mt_prefix + "MailMagazineNumber\tPowerCMS[F]", tag_open + mt_prefix + "MailMagazineNumber${1}" + tag_close),
            (mt_prefix + "MembersLoginCheck\tPowerCMS[F]", tag_open + mt_prefix + "MembersLoginCheck${1}" + tag_close),
            (mt_prefix + "MembersScript\tPowerCMS[F]", tag_open + mt_prefix + "MembersScript${1}" + tag_close),
            (mt_prefix + "ObjectGroupItemClass\tPowerCMS[F]", tag_open + mt_prefix + "ObjectGroupItemClass${1}" + tag_close),
            (mt_prefix + "PageFieldScope\tPowerCMS[F]", tag_open + mt_prefix + "PageFieldScope${1}" + tag_close),
            (mt_prefix + "PagePostCount\tPowerCMS[F]", tag_open + mt_prefix + "PagePostCount${1}" + tag_close),
            (mt_prefix + "PagerCounter\tPowerCMS[F]", tag_open + mt_prefix + "PagerCounter${1}" + tag_close),
            (mt_prefix + "PagerCurrent\tPowerCMS[F]", tag_open + mt_prefix + "PagerCurrent${1}" + tag_close),
            (mt_prefix + "PagerLink\tPowerCMS[F]", tag_open + mt_prefix + "PagerLink${1}" + tag_close),
            (mt_prefix + "PagerNextLink\tPowerCMS[F]", tag_open + mt_prefix + "PagerNextLink${1}" + tag_close),
            (mt_prefix + "PagerPrevLink\tPowerCMS[F]", tag_open + mt_prefix + "PagerPrevLink${1}" + tag_close),
            (mt_prefix + "PagerTotal\tPowerCMS[F]", tag_open + mt_prefix + "PagerTotal${1}" + tag_close),
            (mt_prefix + "Permalink\tPowerCMS[F]", tag_open + mt_prefix + "Permalink${1}" + tag_close),
            (mt_prefix + "PluginPath\tPowerCMS[F]", tag_open + mt_prefix + "PluginPath${1}" + tag_close),
            (mt_prefix + "PluginSetting\tPowerCMS[F]", tag_open + mt_prefix + "PluginSetting${1}" + tag_close),
            (mt_prefix + "PluginVersion\tPowerCMS[F]", tag_open + mt_prefix + "PluginVersion${1}" + tag_close),
            (mt_prefix + "PostFieldsAsStr\tPowerCMS[F]", tag_open + mt_prefix + "PostFieldsAsStr${1}" + tag_close),
            (mt_prefix + "PowerCMSEdition\tPowerCMS[F]", tag_open + mt_prefix + "PowerCMSEdition${1}" + tag_close),
            (mt_prefix + "PowerCMSFilesDir\tPowerCMS[F]", tag_open + mt_prefix + "PowerCMSFilesDir${1}" + tag_close),
            (mt_prefix + "PowerCMSVersion\tPowerCMS[F]", tag_open + mt_prefix + "PowerCMSVersion${1}" + tag_close),
            (mt_prefix + "QueryDump\tPowerCMS[F]", tag_open + mt_prefix + "QueryDump${1}" + tag_close),
            (mt_prefix + "RebuildBlog\tPowerCMS[F]", tag_open + mt_prefix + "RebuildBlog${1}" + tag_close),
            (mt_prefix + "RebuildIndexByBlogId\tPowerCMS[F]", tag_open + mt_prefix + "RebuildIndexByBlogId${1}" + tag_close),
            (mt_prefix + "RebuildIndexById\tPowerCMS[F]", tag_open + mt_prefix + "RebuildIndexById${1}" + tag_close),
            (mt_prefix + "RevisionCount\tPowerCMS[F]", tag_open + mt_prefix + "RevisionCount${1}" + tag_close),
            (mt_prefix + "SidebarAssetCount\tPowerCMS[F]", tag_open + mt_prefix + "SidebarAssetCount${1}" + tag_close),
            (mt_prefix + "StaticFullURL\tPowerCMS[F]", tag_open + mt_prefix + "StaticFullURL${1}" + tag_close),
            (mt_prefix + "TableColumnValue\tPowerCMS[F]", tag_open + mt_prefix + "TableColumnValue${1}" + tag_close),
            (mt_prefix + "TabSplitLine\tPowerCMS[F]", tag_open + mt_prefix + "TabSplitLine${1}" + tag_close),
            (mt_prefix + "TemplateGroupFieldScope\tPowerCMS[F]", tag_open + mt_prefix + "TemplateGroupFieldScope${1}" + tag_close),
            (mt_prefix + "TemplateName\tPowerCMS[F]", tag_open + mt_prefix + "TemplateName${1}" + tag_close),
            (mt_prefix + "TemplateOutput\tPowerCMS[F]", tag_open + mt_prefix + "TemplateOutput${1}" + tag_close),
            (mt_prefix + "TemplateText\tPowerCMS[F]", tag_open + mt_prefix + "TemplateText${1}" + tag_close),
            (mt_prefix + "ThisURL\tPowerCMS[F]", tag_open + mt_prefix + "ThisURL${1}" + tag_close),
            (mt_prefix + "VarDump\tPowerCMS[F]", tag_open + mt_prefix + "VarDump${1}" + tag_close),
            (mt_prefix + "ViewerScript\tPowerCMS[F]", tag_open + mt_prefix + "ViewerScript${1}" + tag_close),
            (mt_prefix + "XMLDocument\tPowerCMS[F]", tag_open + mt_prefix + "XMLDocument${1}" + tag_close),
            (mt_prefix + "Year\tPowerCMS[F]", tag_open + mt_prefix + "Year${1}" + tag_close)
        ], sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS)
